import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { PrismaClient } from "@prisma/client";
import { describe, expect, it } from "vitest";
import { matchIncidentToKnowledgeBase } from "@/modules/troubleshooting/matcher";
import { RepairHandlerRegistry, type PostAssemblyRepairHandler } from "@/modules/troubleshooting/handlers";
import { incidentSchema } from "@/modules/troubleshooting/incident-schema";
import { VERIFIED_TROUBLESHOOTING_RULES } from "@/modules/troubleshooting/seed";
import type { TroubleshootingRule } from "@/modules/troubleshooting/schema";
import { OutputVersionService, hashOutputFile } from "@/modules/output-versioning/service";
import { PostAssemblyRepairCoordinator as ProductionRepairCoordinator, type PostAssemblyRepairInput } from "./repair-coordinator";

// Synthetic authorization for algorithm/candidate tests, never production provenance.
class PostAssemblyRepairCoordinator extends ProductionRepairCoordinator {
  constructor(...args: ConstructorParameters<typeof ProductionRepairCoordinator>) {
    super(args[0], args[1], args[2], args[3], () => true);
  }
}
import { DOUBLE_PUPIL_HANDLER_ID, DOUBLE_PUPIL_HANDLER_VERSION, computeDoublePupilGeometry, createDoublePupilFrame, createDoublePupilPostAssemblyHandler, doublePupilParametersSchema, parseDoublePupilParametersFromState, renderDoublePupilCandidate } from "./double-pupil-handler";
import { DoublePupilValidator } from "./double-pupil-validator";
import { findSmokeRingFfmpegPath } from "./smoke-ring-handler";
import type { QaFinding, QaValidator } from "./types";

const execFileAsync = promisify(execFile);
async function createSchema(client: PrismaClient) { await client.$executeRawUnsafe('CREATE TABLE "PostAssemblyOutputVersion" ("id" TEXT NOT NULL PRIMARY KEY, "projectId" TEXT NOT NULL, "versionNumber" INTEGER NOT NULL, "status" TEXT NOT NULL, "filePath" TEXT NOT NULL, "fileHash" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdFromVersionId" TEXT, "createdByRepairIncidentId" TEXT, "repairRuleId" TEXT, "validationStatus" TEXT NOT NULL, "promotedAt" DATETIME, "rejectedAt" DATETIME, "rollbackReason" TEXT)'); await client.$executeRawUnsafe('CREATE TABLE "PostAssemblyOutputVersionAudit" ("id" TEXT NOT NULL PRIMARY KEY, "projectId" TEXT NOT NULL, "outputVersionId" TEXT, "event" TEXT NOT NULL, "previousCurrentVersionId" TEXT, "newCurrentVersionId" TEXT, "reason" TEXT, "metadata" JSONB NOT NULL DEFAULT \'{}\', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)'); await client.$executeRawUnsafe('CREATE UNIQUE INDEX "PostAssemblyOutputVersion_projectId_versionNumber_key" ON "PostAssemblyOutputVersion"("projectId", "versionNumber")'); await client.$executeRawUnsafe('CREATE UNIQUE INDEX "PostAssemblyOutputVersion_one_current_per_project" ON "PostAssemblyOutputVersion"("projectId") WHERE "status" = \'CURRENT\''); await client.$executeRawUnsafe('CREATE INDEX "PostAssemblyOutputVersion_projectId_status_idx" ON "PostAssemblyOutputVersion"("projectId", "status")'); await client.$executeRawUnsafe('CREATE INDEX "PostAssemblyOutputVersion_projectId_fileHash_idx" ON "PostAssemblyOutputVersion"("projectId", "fileHash")'); await client.$executeRawUnsafe('CREATE INDEX "PostAssemblyOutputVersionAudit_projectId_createdAt_idx" ON "PostAssemblyOutputVersionAudit"("projectId", "createdAt")'); await client.$executeRawUnsafe('CREATE INDEX "PostAssemblyOutputVersionAudit_outputVersionId_createdAt_idx" ON "PostAssemblyOutputVersionAudit"("outputVersionId", "createdAt")'); }
async function createVideo(ffmpegPath: string, filePath: string) { const filter = ["drawbox=x=120:y=75:w=42:h=26:color=0xb4c6d2:t=fill", "drawbox=x=180:y=75:w=42:h=26:color=0xb4c6d2:t=fill", "drawbox=x=124:y=82:w=8:h=12:color=0x182030:t=fill", "drawbox=x=184:y=82:w=8:h=12:color=0x182030:t=fill", "drawbox=x=140:y=82:w=10:h=12:color=0x182030:t=fill", "drawbox=x=200:y=82:w=10:h=12:color=0x182030:t=fill", "drawbox=x=150:y=125:w=20:h=10:color=0x889999:t=fill"].join(","); await execFileAsync(ffmpegPath, ["-y", "-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", "color=c=0x31405f:s=320x180:r=10:d=3", "-vf", filter, "-an", "-c:v", "h264_mf", "-b:v", "1M", filePath], { windowsHide: true, maxBuffer: 2_000_000 }); }
async function withMediaDb<T>(callback: (input: { service: OutputVersionService; root: string; ffmpegPath: string; currentVersion: Awaited<ReturnType<OutputVersionService["registerOriginalOutput"]>> }) => Promise<T>) { const ffmpegPath = await findSmokeRingFfmpegPath(); if (!ffmpegPath) throw new Error("TEST_FFMPEG_NOT_FOUND"); const root = await mkdtemp(path.join(os.tmpdir(), "double-pupil-handler-")); const client = new PrismaClient({ datasources: { db: { url: `file:${path.join(root, "outputs.db").replace(/\\/g, "/")}` } } }); const service = new OutputVersionService(client, async () => undefined); try { await createSchema(client); const currentPath = path.join(root, "final.mp4"); await createVideo(ffmpegPath, currentPath); const currentVersion = await service.registerOriginalOutput({ projectId: "project-double-pupil", filePath: currentPath, validationStatus: "PASS" }); return await callback({ service, root, ffmpegPath, currentVersion }); } finally { await client.$disconnect(); await rm(root, { recursive: true, force: true }); } }

function doubleState(overrides: Record<string, unknown> = {}) { return { sceneNumber: 5, sceneStart: 0, sceneEnd: 3, effectStartLocalTime: .5, effectEndLocalTime: 2.5, leftEyeRegion: { x: 120, y: 75, width: 42, height: 26, space: "PIXELS" }, rightEyeRegion: { x: 180, y: 75, width: 42, height: 26, space: "PIXELS" }, leftOldPupilRegion: { x: 124, y: 82, width: 8, height: 12, space: "PIXELS" }, rightOldPupilRegion: { x: 184, y: 82, width: 8, height: 12, space: "PIXELS" }, leftDesiredPupilRegion: { x: 140, y: 82, width: 10, height: 12, space: "PIXELS" }, rightDesiredPupilRegion: { x: 200, y: 82, width: 10, height: 12, space: "PIXELS" }, eraseMargin: 2, featherAmount: 1, interpolation: "SMOOTHSTEP", blinkWindowsToPreserve: [{ startLocalTime: 1.2, endLocalTime: 1.4 }], ...overrides }; }
function doubleRule(overrides: Partial<TroubleshootingRule> = {}): TroubleshootingRule { const source = VERIFIED_TROUBLESHOOTING_RULES.find(rule => rule.issueId === "DOUBLE_PUPIL_ERASURE_ALIGNMENT")!; return { ...source, autoRepairAllowed: true, verificationStatus: "VERIFIED", ...overrides }; }
function doubleIncident(overrides: Record<string, unknown> = {}) { return incidentSchema.parse({ incidentId: "77777777-7777-4777-8777-777777777777", timestamp: "2026-09-15T00:00:00.000Z", projectId: "project-double-pupil", sceneNumber: 5, stage: "POST_PROCESSING", component: "double-pupil", symptoms: ["Double pupil after gaze patch"], errorMessages: ["DOUBLE_PUPIL"], errorCodes: ["DOUBLE_PUPIL"], firstDivergence: "OLD_PUPIL_ERASURE_ALIGNMENT", expectedState: { doublePupil: false }, actualState: doubleState(), evidence: [{ kind: "old-and-desired-pupil-regions", source: "fixture", value: doubleState() }], runtimeState: { generationStatus: "SUCCESS", outputReady: true }, checkpoint: { generationStatus: "SUCCESS", outputReady: true }, attemptCount: 0, previousRepairAttempts: [], affectedFiles: ["final.mp4"], preserveRequirements: ["Preserve approved Scene 1–4."], ...overrides }); }
function doubleFinding(overrides: Partial<QaFinding> = {}): QaFinding { return { validatorId: "double-pupil", status: "FAIL", sceneNumber: 5, globalTimestamp: .5, sceneLocalTimestamp: .5, expected: { doublePupil: false }, actual: { doublePupil: true }, evidence: ["fixture double pupil"], confidence: 1, severity: "HIGH", suggestedFirstDivergence: "OLD_PUPIL_ERASURE_ALIGNMENT", affectedRegion: "eyes", affectedFile: "final.mp4", symptom: "Double pupil after gaze patch", ...overrides }; }
function coordinatorInput(currentVersion: Awaited<ReturnType<OutputVersionService["registerOriginalOutput"]>>, rule = doubleRule(), incident = doubleIncident(), finding = doubleFinding()): PostAssemblyRepairInput { const match = matchIncidentToKnowledgeBase(incident, [rule]); return { projectId: "project-double-pupil", qaRunId: "qa-double-1", finding, incident, match, matchedRule: rule, currentOutputVersion: currentVersion, approvedManifest: { scenes: [1, 2, 3, 4, 5].map(sceneNumber => ({ sceneNumber, source: `scene-${sceneNumber}.mp4`, durationSec: 3 })) }, approvedSources: ["scene-1.mp4", "scene-2.mp4", "scene-3.mp4", "scene-4.mp4", "scene-5.mp4"], expectedSceneStates: {}, sceneMetadata: {}, checkpoint: { ...doubleState(), generationStatus: "SUCCESS", outputReady: true }, preserveRequirements: ["Preserve approved Scene 1–4."], generationStatus: "SUCCESS", outputReady: true }; }
function failValidator(): QaValidator { return { id: "double-pupil", validate: async () => [{ ...doubleFinding(), status: "FAIL" }] }; }

describe("Reusable double-pupil old-pupil erasure handler", () => {
  it("CASE 1 creates candidate and runs for valid old/desired pupil evidence", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new DoublePupilValidator()]).repair(coordinatorInput(currentVersion)); expect(result.candidateVersionId).not.toBeNull(); expect(result.actionsTaken).toContain("eraseOldPupilResidueWithLocalSclera"); }); });
  it("CASE 2 erases old pupil fully", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new DoublePupilValidator()]).repair(coordinatorInput(currentVersion)); const finding = result.validationResults.find(item => item.validatorId === "double-pupil")?.findings[0]; expect(finding?.status).toBe("PASS"); expect(finding?.actual).toMatchObject({ OLD_PUPIL_FULLY_ERASED: true, DESIRED_PUPIL_PRESENT: true, PUPIL_POSITION_PRESERVED: true, PUPIL_SIZE_STYLE_MATCH: true, GAZE_PRESERVED: true, SCLERA_COLOR_MATCH: true, WHITE_HALO_ABSENT: true, BLINK_PRESERVED: true, SMOKE_RING_PRESERVED: true }); }); });
  it("CASE 3 confirms double pupil is absent after repair", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new DoublePupilValidator()]).repair(coordinatorInput(currentVersion)); expect(result.validationResults.find(item => item.validatorId === "double-pupil")?.findings[0]?.actual).toMatchObject({ DOUBLE_PUPIL_ABSENT: true }); }); });
  it("CASE 4 keeps desired pupil present", () => { const parsed = parseDoublePupilParametersFromState(doubleState(), 5, "in", "out"); expect("value" in parsed).toBe(true); });
  it("CASE 5 preserves desired pupil position", () => { const parameters = doublePupilParametersSchema.parse({ ...doubleState(), candidateInputPath: "in", candidateOutputPath: "out" }); const geometry = computeDoublePupilGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 }); if ("error" in geometry) throw new Error(geometry.error); expect(geometry.left?.desiredPupil.x).toBe(140); });
  it("CASE 6 preserves desired pupil size/style", () => { const parameters = doublePupilParametersSchema.parse({ ...doubleState(), candidateInputPath: "in", candidateOutputPath: "out" }); const geometry = computeDoublePupilGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 }); if ("error" in geometry) throw new Error(geometry.error); expect(geometry.left?.desiredPupil.width).toBe(10); expect(geometry.left?.desiredPupil.height).toBe(12); });
  it("CASE 7 preserves gaze", () => { expect(parseDoublePupilParametersFromState(doubleState(), 5, "in", "out")).toHaveProperty("value"); });
  it("CASE 8 reconstructs with local sclera", () => { const parameters = doublePupilParametersSchema.parse({ ...doubleState(), candidateInputPath: "in", candidateOutputPath: "out" }); const geometry = computeDoublePupilGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 }); if ("error" in geometry) throw new Error(geometry.error); const frame = createDoublePupilFrame(parameters, { width: 320, height: 180, fps: 10, duration: 3 }, 1, geometry, { left: { color: { r: 180, g: 198, b: 210 }, sampleCount: 20, maxDeviation: 0 }, right: { color: { r: 180, g: 198, b: 210 }, sampleCount: 20, maxDeviation: 0 } }); expect(frame[(88 * 320 + 128) * 4]).toBe(180); });
  it("CASE 9 does not create white halo", () => { const parameters = doublePupilParametersSchema.parse({ ...doubleState(), candidateInputPath: "in", candidateOutputPath: "out" }); const geometry = computeDoublePupilGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 }); if ("error" in geometry) throw new Error(geometry.error); const frame = createDoublePupilFrame(parameters, { width: 320, height: 180, fps: 10, duration: 3 }, 1, geometry, { left: { color: { r: 180, g: 198, b: 210 }, sampleCount: 1, maxDeviation: 0 }, right: { color: { r: 180, g: 198, b: 210 }, sampleCount: 1, maxDeviation: 0 } }); expect(frame[(88 * 320 + 128) * 4]).not.toBe(255); });
  it("CASE 10 preserves blink window", () => { const parameters = doublePupilParametersSchema.parse({ ...doubleState(), candidateInputPath: "in", candidateOutputPath: "out" }); const geometry = computeDoublePupilGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 }); if ("error" in geometry) throw new Error(geometry.error); expect(createDoublePupilFrame(parameters, { width: 320, height: 180, fps: 10, duration: 3 }, 1.3, geometry, { left: null, right: null }).every(value => value === 0)).toBe(true); });
  it("CASE 11 preserves smoke fixture", () => { const parameters = doublePupilParametersSchema.parse({ ...doubleState(), candidateInputPath: "in", candidateOutputPath: "out" }); const geometry = computeDoublePupilGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 }); if ("error" in geometry) throw new Error(geometry.error); const frame = createDoublePupilFrame(parameters, { width: 320, height: 180, fps: 10, duration: 3 }, 1, geometry, { left: { color: { r: 1, g: 1, b: 1 }, sampleCount: 1, maxDeviation: 0 }, right: { color: { r: 1, g: 1, b: 1 }, sampleCount: 1, maxDeviation: 0 } }); expect(frame[(130 * 320 + 160) * 4 + 3]).toBe(0); });
  it("CASE 12 limits changes to FRAME_REGION", () => { const parameters = doublePupilParametersSchema.parse({ ...doubleState(), candidateInputPath: "in", candidateOutputPath: "out" }); const geometry = computeDoublePupilGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 }); if ("error" in geometry) throw new Error(geometry.error); const frame = createDoublePupilFrame(parameters, { width: 320, height: 180, fps: 10, duration: 3 }, 1, geometry, { left: { color: { r: 1, g: 1, b: 1 }, sampleCount: 1, maxDeviation: 0 }, right: { color: { r: 1, g: 1, b: 1 }, sampleCount: 1, maxDeviation: 0 } }); expect(frame[(20 * 320 + 20) * 4 + 3]).toBe(0); });
  it("CASE 13 missing old pupil evidence returns NEEDS_REVIEW", () => { expect(parseDoublePupilParametersFromState(doubleState({ leftOldPupilRegion: undefined, rightOldPupilRegion: undefined }), 5, "in", "out")).toEqual({ error: "MISSING_OLD_PUPIL_REGION" }); });
  it("CASE 14 missing desired pupil evidence returns NEEDS_REVIEW", () => { expect(parseDoublePupilParametersFromState(doubleState({ leftDesiredPupilRegion: undefined }), 5, "in", "out")).toEqual({ error: "MISSING_DESIRED_PUPIL_REGION" }); });
  it("CASE 15 ambiguous characters are not guessed", () => { expect(parseDoublePupilParametersFromState(doubleState({ multipleCharacters: true }), 5, "in", "out")).toEqual({ error: "AMBIGUOUS_DOUBLE_PUPIL_TARGET" }); });
  it("CASE 16 unsafe erase mask near eye boundary returns NEEDS_REVIEW", () => { const parameters = doublePupilParametersSchema.parse({ ...doubleState({ leftOldPupilRegion: { x: 120, y: 82, width: 8, height: 12, space: "PIXELS" } }), candidateInputPath: "in", candidateOutputPath: "out" }); expect(computeDoublePupilGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 })).toEqual({ error: "ERASE_MASK_UNSAFE_FOR_EYE_BOUNDARY" }); });
  it("CASE 17 promotes after validation PASS", async () => { await withMediaDb(async ({ service, currentVersion }) => { expect((await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new DoublePupilValidator()]).repair(coordinatorInput(currentVersion))).status).toBe("PROMOTED"); }); });
  it("CASE 18 validation FAIL rejects candidate and preserves CURRENT", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [failValidator()]).repair(coordinatorInput(currentVersion)); expect(result.status).toBe("REPAIR_FAILED"); expect((await service.getCurrentOutput("project-double-pupil"))?.id).toBe(currentVersion.id); }); });
  it("CASE 19 handler never writes CURRENT directly", async () => { await withMediaDb(async ({ service, currentVersion }) => { const before = await readFile(currentVersion.filePath); const candidate = await service.createCandidate({ projectId: "project-double-pupil", sourcePath: currentVersion.filePath, currentVersionId: currentVersion.id }); const result = await createDoublePupilPostAssemblyHandler().handlePostAssembly({ incident: doubleIncident(), rule: doubleRule(), candidateVersionId: candidate.id, candidatePath: candidate.filePath, currentOutputPath: currentVersion.filePath, repairAttemptId: "attempt" }); expect(result.filesChanged).toEqual([candidate.filePath]); expect(await readFile(currentVersion.filePath)).toEqual(before); }); });
  it("CASE 20 handler throw rejects candidate and creates report/handoff", async () => { await withMediaDb(async ({ service, currentVersion }) => { const throwing: PostAssemblyRepairHandler = { ...createDoublePupilPostAssemblyHandler(), handlePostAssembly: async () => { throw new Error("double pupil handler exploded"); } }; const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry([throwing]), [], async () => ({ jsonReportPath: "json", markdownReportPath: "md" })).repair(coordinatorInput(currentVersion)); expect(result.status).toBe("REPAIR_FAILED"); expect(result.rejectedCandidateId).toBe(result.candidateVersionId); expect(result.codexHandoffText).toContain("CODEX HANDOFF"); }); });
  it("CASE 21 same input and parameters produce deterministic output", async () => { await withMediaDb(async ({ ffmpegPath, root, currentVersion }) => { const firstPath = path.join(root, "double-1.mp4"); const secondPath = path.join(root, "double-2.mp4"); const first = doublePupilParametersSchema.parse({ ...doubleState(), candidateInputPath: currentVersion.filePath, candidateOutputPath: firstPath }); await renderDoublePupilCandidate(first, ffmpegPath); await renderDoublePupilCandidate({ ...first, candidateOutputPath: secondPath }, ffmpegPath); expect(await hashOutputFile(firstPath)).toBe(await hashOutputFile(secondPath)); }); });
  it("CASE 22 retry limit prevents loop", async () => { await withMediaDb(async ({ service, currentVersion }) => { let calls = 0; const handler: PostAssemblyRepairHandler = { ...createDoublePupilPostAssemblyHandler(), handlePostAssembly: async () => { calls += 1; throw new Error("must not run"); } }; const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry([handler]), []).repair(coordinatorInput(currentVersion, doubleRule(), doubleIncident({ previousRepairAttempts: [{ ruleId: "DOUBLE_PUPIL_ERASURE_ALIGNMENT", status: "REPAIR_FAILED", at: "2026-09-15T00:00:00.000Z" }] }))); expect(result.status).toBe("RETRY_LIMIT_REACHED"); expect(calls).toBe(0); }); });
  it("CASE 23 preserves generationStatus SUCCESS", async () => { await withMediaDb(async ({ service, currentVersion }) => { expect((await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new DoublePupilValidator()]).repair(coordinatorInput(currentVersion))).generationStatus).toBe("SUCCESS"); }); });
  it("CASE 24 preserves outputReady true", async () => { await withMediaDb(async ({ service, currentVersion }) => { expect((await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new DoublePupilValidator()]).repair(coordinatorInput(currentVersion))).outputReady).toBe(true); }); });
  it("CASE 25 production registry contains double-pupil handler", () => { expect(new RepairHandlerRegistry().getPostAssembly("DOUBLE_PUPIL_ERASURE_ALIGNMENT")?.postAssembly).toMatchObject({ handlerId: DOUBLE_PUPIL_HANDLER_ID, handlerVersion: DOUBLE_PUPIL_HANDLER_VERSION, supportsPostAssembly: true, repairScope: "FRAME_REGION", mutatesOutputFile: true, requiresCandidate: true }); });
  it("CASE 26 leaves white-halo handler registered and unchanged", () => { expect(new RepairHandlerRegistry().getPostAssembly("GAZE_WHITE_HALO_COMPOSITING")).toBeDefined(); });
  it("CASE 27 leaves gaze handler registered and unchanged", () => { expect(new RepairHandlerRegistry().getPostAssembly("GAZE_NOT_TO_MONITOR")).toBeDefined(); });
  it("CASE 28 blocks unproven double-pupil auto repair", () => { expect(VERIFIED_TROUBLESHOOTING_RULES.find(rule => rule.issueId === "DOUBLE_PUPIL_ERASURE_ALIGNMENT")?.autoRepairAllowed).toBe(false); });
});
