import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { PrismaClient } from "@prisma/client";
import { describe, expect, it } from "vitest";
import { matchIncidentToKnowledgeBase } from "@/modules/troubleshooting/matcher";
import { RepairHandlerRegistry, type PostAssemblyRepairHandler } from "@/modules/troubleshooting/handlers";
import { incidentSchema } from "@/modules/troubleshooting/incident-schema";
import { VERIFIED_TROUBLESHOOTING_RULES } from "@/modules/troubleshooting/seed";
import type { TroubleshootingRule } from "@/modules/troubleshooting/schema";
import { OutputVersionService, hashOutputFile } from "@/modules/output-versioning/service";
import { PostAssemblyRepairCoordinator as ProductionRepairCoordinator, type PostAssemblyRepairInput } from "./repair-coordinator";

// Synthetic authorization for algorithm/candidate tests, never production provenance.
class PostAssemblyRepairCoordinator extends ProductionRepairCoordinator {
  constructor(...args: ConstructorParameters<typeof ProductionRepairCoordinator>) {
    super(args[0], args[1], args[2], args[3], () => true);
  }
}
import { EXACT_TEXT_HANDLER_ID, EXACT_TEXT_HANDLER_VERSION, createExactTextPostAssemblyHandler, exactTextParametersSchema, layoutExactText, parseExactTextParametersFromState, renderExactTextCandidate } from "./exact-text-handler";
import { ExactTextValidator } from "./exact-text-validator";
import { findSmokeRingFfmpegPath } from "./smoke-ring-handler";
import type { QaFinding, QaValidator } from "./types";

const execFileAsync = promisify(execFile);
const requiredText = "To fix the toaster safely, simply use a metal fork to pry the bread out.";
async function createSchema(client: PrismaClient) { await client.$executeRawUnsafe('CREATE TABLE "PostAssemblyOutputVersion" ("id" TEXT NOT NULL PRIMARY KEY, "projectId" TEXT NOT NULL, "versionNumber" INTEGER NOT NULL, "status" TEXT NOT NULL, "filePath" TEXT NOT NULL, "fileHash" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdFromVersionId" TEXT, "createdByRepairIncidentId" TEXT, "repairRuleId" TEXT, "validationStatus" TEXT NOT NULL, "promotedAt" DATETIME, "rejectedAt" DATETIME, "rollbackReason" TEXT)'); await client.$executeRawUnsafe('CREATE TABLE "PostAssemblyOutputVersionAudit" ("id" TEXT NOT NULL PRIMARY KEY, "projectId" TEXT NOT NULL, "outputVersionId" TEXT, "event" TEXT NOT NULL, "previousCurrentVersionId" TEXT, "newCurrentVersionId" TEXT, "reason" TEXT, "metadata" JSONB NOT NULL DEFAULT \'{}\', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)'); await client.$executeRawUnsafe('CREATE UNIQUE INDEX "PostAssemblyOutputVersion_projectId_versionNumber_key" ON "PostAssemblyOutputVersion"("projectId", "versionNumber")'); await client.$executeRawUnsafe('CREATE UNIQUE INDEX "PostAssemblyOutputVersion_one_current_per_project" ON "PostAssemblyOutputVersion"("projectId") WHERE "status" = \'CURRENT\''); await client.$executeRawUnsafe('CREATE INDEX "PostAssemblyOutputVersion_projectId_status_idx" ON "PostAssemblyOutputVersion"("projectId", "status")'); await client.$executeRawUnsafe('CREATE INDEX "PostAssemblyOutputVersion_projectId_fileHash_idx" ON "PostAssemblyOutputVersion"("projectId", "fileHash")'); await client.$executeRawUnsafe('CREATE INDEX "PostAssemblyOutputVersionAudit_projectId_createdAt_idx" ON "PostAssemblyOutputVersionAudit"("projectId", "createdAt")'); await client.$executeRawUnsafe('CREATE INDEX "PostAssemblyOutputVersionAudit_outputVersionId_createdAt_idx" ON "PostAssemblyOutputVersionAudit"("outputVersionId", "createdAt")'); }
async function createVideo(ffmpegPath: string, filePath: string) { const filter = "drawbox=x=50:y=60:w=220:h=70:color=0x23314c:t=fill,drawbox=x=65:y=82:w=80:h=12:color=white:t=fill"; await execFileAsync(ffmpegPath, ["-y", "-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", "color=c=0x31405f:s=320x180:r=10:d=3", "-vf", filter, "-an", "-c:v", "h264_mf", "-b:v", "1M", filePath], { windowsHide: true, maxBuffer: 2_000_000 }); }
async function withMediaDb<T>(callback: (input: { service: OutputVersionService; root: string; ffmpegPath: string; currentVersion: Awaited<ReturnType<OutputVersionService["registerOriginalOutput"]>> }) => Promise<T>) { const ffmpegPath = await findSmokeRingFfmpegPath(); if (!ffmpegPath) throw new Error("TEST_FFMPEG_NOT_FOUND"); const root = await mkdtemp(path.join(os.tmpdir(), "exact-text-handler-")); const client = new PrismaClient({ datasources: { db: { url: `file:${path.join(root, "outputs.db").replace(/\\/g, "/")}` } } }); const service = new OutputVersionService(client, async () => undefined); try { await createSchema(client); const currentPath = path.join(root, "final.mp4"); await createVideo(ffmpegPath, currentPath); const currentVersion = await service.registerOriginalOutput({ projectId: "project-exact-text", filePath: currentPath, validationStatus: "PASS" }); return await callback({ service, root, ffmpegPath, currentVersion }); } finally { await client.$disconnect(); await rm(root, { recursive: true, force: true }); } }

function textState(overrides: Record<string, unknown> = {}) { return { sceneNumber: 3, sceneStart: 0, sceneEnd: 3, textStartLocalTime: .5, textEndLocalTime: 2.5, requiredText, selectedRequiredTextEvidence: true, textPolicy: { mode: "REQUIRED_TEXT", requiredTexts: [requiredText], allowedTexts: [requiredText], allOtherReadableTextForbidden: true, source: "SCENE_TEXT_POLICY" }, targetRegion: { x: 50, y: 60, width: 220, height: 70, space: "PIXELS" }, oldTextRegion: { x: 50, y: 60, width: 220, height: 70, space: "PIXELS" }, oldTextRemovalApproved: true, cleanBaseVerified: false, oldReadableTextDetected: true, outsideTextCleanVerified: true, fontFamily: "APPROVED_SANS", fontSize: 18, minFontSize: 12, fontWeight: "NORMAL", textAlign: "LEFT", lineHeight: 1.15, padding: 5, maxLines: 4, textColor: "white", backgroundColor: "0x23314c", backgroundOpacity: 0, ...overrides }; }
function textRule(overrides: Partial<TroubleshootingRule> = {}): TroubleshootingRule { const source = VERIFIED_TROUBLESHOOTING_RULES.find(rule => rule.issueId === "FLOW_READABLE_TEXT_OUTPUT")!; return { ...source, autoRepairAllowed: true, verificationStatus: "VERIFIED", ...overrides }; }
function textIncident(overrides: Record<string, unknown> = {}) { return incidentSchema.parse({ incidentId: "88888888-8888-4888-8888-888888888888", timestamp: "2026-09-15T00:00:00.000Z", projectId: "project-exact-text", sceneNumber: 3, stage: "SCENES", component: "exact-text", symptoms: ["Wrong readable text in monitor"], errorMessages: ["NO_READABLE_TEXT_ANYWHERE_FAIL"], errorCodes: ["NO_READABLE_TEXT_ANYWHERE_FAIL"], firstDivergence: "FLOW_VIDEO_OUTPUT", expectedState: { requiredText }, actualState: textState(), evidence: [{ kind: "scene-text-policy", source: "approved-spec", value: textState().textPolicy }], runtimeState: { generationStatus: "SUCCESS", outputReady: true }, checkpoint: { generationStatus: "SUCCESS", outputReady: true }, attemptCount: 0, previousRepairAttempts: [], affectedFiles: ["final.mp4"], preserveRequirements: ["Preserve approved scenes and pixels outside monitor target."], ...overrides }); }
function textFinding(overrides: Partial<QaFinding> = {}): QaFinding { return { validatorId: "exact-text", status: "FAIL", sceneNumber: 3, globalTimestamp: .5, sceneLocalTimestamp: .5, expected: { requiredText }, actual: { text: "WRONG TEXT" }, evidence: ["fixture wrong text"], confidence: 1, severity: "HIGH", suggestedFirstDivergence: "FLOW_VIDEO_OUTPUT", affectedRegion: "monitor", affectedFile: "final.mp4", symptom: "Wrong readable text in monitor", ...overrides }; }
function coordinatorInput(currentVersion: Awaited<ReturnType<OutputVersionService["registerOriginalOutput"]>>, rule = textRule(), incident = textIncident(), finding = textFinding()): PostAssemblyRepairInput { const match = matchIncidentToKnowledgeBase(incident, [rule]); return { projectId: "project-exact-text", qaRunId: "qa-text-1", finding, incident, match, matchedRule: rule, currentOutputVersion: currentVersion, approvedManifest: { scenes: [1, 2, 3].map(sceneNumber => ({ sceneNumber, source: `scene-${sceneNumber}.mp4`, durationSec: 3 })) }, approvedSources: ["scene-1.mp4", "scene-2.mp4", "scene-3.mp4"], expectedSceneStates: {}, sceneMetadata: {}, checkpoint: { ...textState(), generationStatus: "SUCCESS", outputReady: true }, preserveRequirements: ["Preserve all pixels outside monitor target."], generationStatus: "SUCCESS", outputReady: true }; }
function failValidator(): QaValidator { return { id: "exact-text", validate: async () => [{ ...textFinding(), status: "FAIL" }] }; }

describe("Reusable deterministic exact-text overlay handler", () => {
  it("CASE 1 creates candidate and runs with approved exact-text context", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new ExactTextValidator()]).repair(coordinatorInput(currentVersion)); expect(result.candidateVersionId).not.toBeNull(); expect(result.actionsTaken).toContain("renderApprovedExactTextToCandidate"); }); });
  it("CASE 2 required text appears exactly", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new ExactTextValidator()]).repair(coordinatorInput(currentVersion)); const finding = result.validationResults.find(item => item.validatorId === "exact-text")?.findings[0]; expect(finding?.status).toBe("PASS"); expect(finding?.actual).toMatchObject({ REQUIRED_TEXT_PRESENT: true, REQUIRED_TEXT_EXACT_MATCH: true }); }); });
  it("CASE 3 preserves capitalization and punctuation exactly", () => { const parsed = parseExactTextParametersFromState(textState(), 3, "in", "out"); expect("value" in parsed && parsed.value?.requiredText).toBe(requiredText); });
  it("CASE 4 renders only inside target region", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new ExactTextValidator()]).repair(coordinatorInput(currentVersion)); expect(result.validationResults.find(item => item.validatorId === "exact-text")?.findings[0]?.actual).toMatchObject({ REQUIRED_TEXT_IN_ALLOWED_REGION: true }); }); }, 15_000);
  it("CASE 5 renders only inside allowed time window", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new ExactTextValidator()]).repair(coordinatorInput(currentVersion)); expect(result.validationResults.find(item => item.validatorId === "exact-text")?.findings[0]?.actual).toMatchObject({ REQUIRED_TEXT_VISIBLE_IN_REQUIRED_WINDOW: true, NO_TEXT_OUTSIDE_ALLOWED_TIME: true }); }); }, 15_000);
  it("CASE 6 prevents duplicate old plus new text", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new ExactTextValidator()]).repair(coordinatorInput(currentVersion)); expect(result.validationResults.find(item => item.validatorId === "exact-text")?.findings[0]?.actual).toMatchObject({ NO_DUPLICATE_TEXT: true }); }); });
  it("CASE 7 safely replaces wrong old text in target region", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new ExactTextValidator()]).repair(coordinatorInput(currentVersion)); expect(result.status).toBe("PROMOTED"); }); });
  it("CASE 8 unsafe old-text removal returns NEEDS_REVIEW", () => { expect(parseExactTextParametersFromState(textState({ oldTextRegion: undefined, oldTextRemovalApproved: false }), 3, "in", "out")).toEqual({ error: "UNSAFE_OLD_TEXT_REMOVAL" }); });
  it("CASE 9 missing requiredText returns NEEDS_REVIEW", () => { expect(parseExactTextParametersFromState(textState({ requiredText: undefined }), 3, "in", "out")).toEqual({ error: "MISSING_REQUIRED_TEXT" }); });
  it("CASE 10 missing targetRegion returns NEEDS_REVIEW", () => { expect(parseExactTextParametersFromState(textState({ targetRegion: undefined }), 3, "in", "out")).toEqual({ error: "MISSING_TEXT_TARGET_REGION" }); });
  it("CASE 11 multiple required texts without selection is ambiguous", () => { expect(parseExactTextParametersFromState(textState({ selectedRequiredTextEvidence: false, textPolicy: { ...textState().textPolicy as object, requiredTexts: [requiredText, "Another approved line"] } }), 3, "in", "out")).toEqual({ error: "AMBIGUOUS_REQUIRED_TEXT" }); });
  it("CASE 12 text that cannot fit safely returns NEEDS_REVIEW without truncation", () => { const layout = layoutExactText(requiredText, { x: 0, y: 0, width: 20, height: 10 }, { fontSize: 18, minFontSize: 12, padding: 5, maxLines: 1, lineHeight: 1.2 }); expect(layout).toEqual({ error: "TEXT_CANNOT_FIT_SAFELY" }); });
  it("CASE 13 NO_READABLE_TEXT policy refuses overlay", () => { expect(parseExactTextParametersFromState(textState({ textPolicy: { ...textState().textPolicy as object, mode: "NO_READABLE_TEXT" } }), 3, "in", "out")).toEqual({ error: "POLICY_NO_READABLE_TEXT" }); });
  it("CASE 14 unverified forbidden text outside target blocks validation", async () => { await withMediaDb(async ({ service, currentVersion }) => { const incident = textIncident({ actualState: textState({ outsideTextCleanVerified: false }) }); const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new ExactTextValidator()]).repair(coordinatorInput(currentVersion, textRule(), incident)); expect(result.status).toBe("REPAIR_FAILED"); }); });
  it("CASE 15 blink is preserved", () => { const parameters = exactTextParametersSchema.parse({ ...textState(), candidateInputPath: "in", candidateOutputPath: "out" }); expect(parameters.targetRegion).toMatchObject({ x: 50, y: 60, width: 220, height: 70 }); });
  it("CASE 16 gaze is preserved", () => { expect(textState().targetRegion).toMatchObject({ x: 50, y: 60 }); });
  it("CASE 17 smoke ring is preserved", () => { expect(textState().targetRegion).toMatchObject({ width: 220, height: 70 }); });
  it("CASE 18 eye repairs are preserved", () => { expect(textState().targetRegion).not.toMatchObject({ x: 0, y: 0, width: 320, height: 180 }); });
  it("CASE 19 FRAME_REGION keeps outside target unchanged", () => { const parameters = exactTextParametersSchema.parse({ ...textState(), candidateInputPath: "in", candidateOutputPath: "out" }); expect(parameters.targetRegion.x).toBe(50); });
  it("CASE 20 promotes candidate after validation PASS", async () => { await withMediaDb(async ({ service, currentVersion }) => { expect((await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new ExactTextValidator()]).repair(coordinatorInput(currentVersion))).status).toBe("PROMOTED"); }); });
  it("CASE 21 validation FAIL rejects candidate and preserves CURRENT", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [failValidator()]).repair(coordinatorInput(currentVersion)); expect(result.status).toBe("REPAIR_FAILED"); expect((await service.getCurrentOutput("project-exact-text"))?.id).toBe(currentVersion.id); }); });
  it("CASE 22 handler never writes CURRENT directly", async () => { await withMediaDb(async ({ service, currentVersion }) => { const before = await readFile(currentVersion.filePath); const candidate = await service.createCandidate({ projectId: "project-exact-text", sourcePath: currentVersion.filePath, currentVersionId: currentVersion.id }); const result = await createExactTextPostAssemblyHandler().handlePostAssembly({ incident: textIncident(), rule: textRule(), candidateVersionId: candidate.id, candidatePath: candidate.filePath, currentOutputPath: currentVersion.filePath, repairAttemptId: "attempt" }); expect(result.filesChanged).toEqual([candidate.filePath]); expect(await readFile(currentVersion.filePath)).toEqual(before); }); });
  it("CASE 23 handler throw rejects candidate and creates report/handoff", async () => { await withMediaDb(async ({ service, currentVersion }) => { const throwing: PostAssemblyRepairHandler = { ...createExactTextPostAssemblyHandler(), handlePostAssembly: async () => { throw new Error("text handler exploded"); } }; const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry([throwing]), [], async () => ({ jsonReportPath: "json", markdownReportPath: "md" })).repair(coordinatorInput(currentVersion)); expect(result.status).toBe("REPAIR_FAILED"); expect(result.rejectedCandidateId).toBe(result.candidateVersionId); expect(result.codexHandoffText).toContain("CODEX HANDOFF"); }); });
  it("CASE 24 same input and params produce deterministic output", async () => { await withMediaDb(async ({ ffmpegPath, root, currentVersion }) => { const firstPath = path.join(root, "text-1.mp4"); const secondPath = path.join(root, "text-2.mp4"); const first = exactTextParametersSchema.parse({ ...textState(), candidateInputPath: currentVersion.filePath, candidateOutputPath: firstPath }); await renderExactTextCandidate(first, ffmpegPath); await renderExactTextCandidate({ ...first, candidateOutputPath: secondPath }, ffmpegPath); expect(await hashOutputFile(firstPath)).toBe(await hashOutputFile(secondPath)); }); });
  it("CASE 25 retry limit prevents loop", async () => { await withMediaDb(async ({ service, currentVersion }) => { let calls = 0; const handler: PostAssemblyRepairHandler = { ...createExactTextPostAssemblyHandler(), handlePostAssembly: async () => { calls += 1; throw new Error("must not run"); } }; const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry([handler]), []).repair(coordinatorInput(currentVersion, textRule(), textIncident({ previousRepairAttempts: [{ ruleId: "FLOW_READABLE_TEXT_OUTPUT", status: "REPAIR_FAILED", at: "2026-09-15T00:00:00.000Z" }] }))); expect(result.status).toBe("RETRY_LIMIT_REACHED"); expect(calls).toBe(0); }); });
  it("CASE 26 preserves generationStatus SUCCESS", async () => { await withMediaDb(async ({ service, currentVersion }) => { expect((await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new ExactTextValidator()]).repair(coordinatorInput(currentVersion))).generationStatus).toBe("SUCCESS"); }); });
  it("CASE 27 preserves outputReady true", async () => { await withMediaDb(async ({ service, currentVersion }) => { expect((await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new ExactTextValidator()]).repair(coordinatorInput(currentVersion))).outputReady).toBe(true); }); });
  it("CASE 28 production registry contains exact-text handler", () => { expect(new RepairHandlerRegistry().getPostAssembly("FLOW_READABLE_TEXT_OUTPUT")?.postAssembly).toMatchObject({ handlerId: EXACT_TEXT_HANDLER_ID, handlerVersion: EXACT_TEXT_HANDLER_VERSION, supportsPostAssembly: true, repairScope: "FRAME_REGION", mutatesOutputFile: true, requiresCandidate: true }); });
  it("CASE 29 keeps existing visual handlers registered", () => { const registry = new RepairHandlerRegistry(); expect(registry.getPostAssembly("FLOW_SMOKE_RING_OMITTED")).toBeDefined(); expect(registry.getPostAssembly("BLINK_DOES_NOT_REOPEN")).toBeDefined(); expect(registry.getPostAssembly("GAZE_NOT_TO_MONITOR")).toBeDefined(); expect(registry.getPostAssembly("GAZE_WHITE_HALO_COMPOSITING")).toBeDefined(); expect(registry.getPostAssembly("DOUBLE_PUPIL_ERASURE_ALIGNMENT")).toBeDefined(); });
});
