import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { PrismaClient } from "@prisma/client";
import { describe, expect, it } from "vitest";
import { matchIncidentToKnowledgeBase } from "@/modules/troubleshooting/matcher";
import { RepairHandlerRegistry, type PostAssemblyRepairHandler } from "@/modules/troubleshooting/handlers";
import { incidentSchema } from "@/modules/troubleshooting/incident-schema";
import { VERIFIED_TROUBLESHOOTING_RULES } from "@/modules/troubleshooting/seed";
import type { TroubleshootingRule } from "@/modules/troubleshooting/schema";
import { OutputVersionService, hashOutputFile } from "@/modules/output-versioning/service";
import { PostAssemblyRepairCoordinator as ProductionRepairCoordinator, type PostAssemblyRepairInput } from "./repair-coordinator";

// Synthetic authorization for algorithm/candidate tests, never production provenance.
class PostAssemblyRepairCoordinator extends ProductionRepairCoordinator {
  constructor(...args: ConstructorParameters<typeof ProductionRepairCoordinator>) {
    super(args[0], args[1], args[2], args[3], () => true);
  }
}
import { WHITE_HALO_HANDLER_ID, WHITE_HALO_HANDLER_VERSION, computeHaloGeometry, createWhiteHaloFrame, createWhiteHaloPostAssemblyHandler, parseWhiteHaloParametersFromState, renderWhiteHaloCandidate, whiteHaloParametersSchema } from "./white-halo-handler";
import { WhiteHaloValidator } from "./white-halo-validator";
import { findSmokeRingFfmpegPath } from "./smoke-ring-handler";
import type { QaFinding, QaValidator } from "./types";

const execFileAsync = promisify(execFile);
async function createSchema(client: PrismaClient) { await client.$executeRawUnsafe('CREATE TABLE "PostAssemblyOutputVersion" ("id" TEXT NOT NULL PRIMARY KEY, "projectId" TEXT NOT NULL, "versionNumber" INTEGER NOT NULL, "status" TEXT NOT NULL, "filePath" TEXT NOT NULL, "fileHash" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdFromVersionId" TEXT, "createdByRepairIncidentId" TEXT, "repairRuleId" TEXT, "validationStatus" TEXT NOT NULL, "promotedAt" DATETIME, "rejectedAt" DATETIME, "rollbackReason" TEXT)'); await client.$executeRawUnsafe('CREATE TABLE "PostAssemblyOutputVersionAudit" ("id" TEXT NOT NULL PRIMARY KEY, "projectId" TEXT NOT NULL, "outputVersionId" TEXT, "event" TEXT NOT NULL, "previousCurrentVersionId" TEXT, "newCurrentVersionId" TEXT, "reason" TEXT, "metadata" JSONB NOT NULL DEFAULT \'{}\', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)'); await client.$executeRawUnsafe('CREATE UNIQUE INDEX "PostAssemblyOutputVersion_projectId_versionNumber_key" ON "PostAssemblyOutputVersion"("projectId", "versionNumber")'); await client.$executeRawUnsafe('CREATE UNIQUE INDEX "PostAssemblyOutputVersion_one_current_per_project" ON "PostAssemblyOutputVersion"("projectId") WHERE "status" = \'CURRENT\''); await client.$executeRawUnsafe('CREATE INDEX "PostAssemblyOutputVersion_projectId_status_idx" ON "PostAssemblyOutputVersion"("projectId", "status")'); await client.$executeRawUnsafe('CREATE INDEX "PostAssemblyOutputVersion_projectId_fileHash_idx" ON "PostAssemblyOutputVersion"("projectId", "fileHash")'); await client.$executeRawUnsafe('CREATE INDEX "PostAssemblyOutputVersionAudit_projectId_createdAt_idx" ON "PostAssemblyOutputVersionAudit"("projectId", "createdAt")'); await client.$executeRawUnsafe('CREATE INDEX "PostAssemblyOutputVersionAudit_outputVersionId_createdAt_idx" ON "PostAssemblyOutputVersionAudit"("outputVersionId", "createdAt")'); }
async function createVideo(ffmpegPath: string, filePath: string) { const filter = ["drawbox=x=120:y=75:w=42:h=26:color=0xb4c6d2:t=fill", "drawbox=x=180:y=75:w=42:h=26:color=0xb4c6d2:t=fill", "drawbox=x=132:y=80:w=22:h=16:color=white:t=fill", "drawbox=x=192:y=80:w=22:h=16:color=white:t=fill", "drawbox=x=138:y=82:w=10:h=12:color=0x182030:t=fill", "drawbox=x=198:y=82:w=10:h=12:color=0x182030:t=fill", "drawbox=x=150:y=125:w=20:h=10:color=0x889999:t=fill"].join(","); await execFileAsync(ffmpegPath, ["-y", "-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", "color=c=0x31405f:s=320x180:r=10:d=3", "-vf", filter, "-an", "-c:v", "h264_mf", "-b:v", "1M", filePath], { windowsHide: true, maxBuffer: 2_000_000 }); }
async function withMediaDb<T>(callback: (input: { service: OutputVersionService; root: string; ffmpegPath: string; currentVersion: Awaited<ReturnType<OutputVersionService["registerOriginalOutput"]>> }) => Promise<T>) { const ffmpegPath = await findSmokeRingFfmpegPath(); if (!ffmpegPath) throw new Error("TEST_FFMPEG_NOT_FOUND"); const root = await mkdtemp(path.join(os.tmpdir(), "white-halo-handler-")); const client = new PrismaClient({ datasources: { db: { url: `file:${path.join(root, "outputs.db").replace(/\\/g, "/")}` } } }); const service = new OutputVersionService(client, async () => undefined); try { await createSchema(client); const currentPath = path.join(root, "final.mp4"); await createVideo(ffmpegPath, currentPath); const currentVersion = await service.registerOriginalOutput({ projectId: "project-white-halo", filePath: currentPath, validationStatus: "PASS" }); return await callback({ service, root, ffmpegPath, currentVersion }); } finally { await client.$disconnect(); await rm(root, { recursive: true, force: true }); } }

function haloState(overrides: Record<string, unknown> = {}) { return { sceneNumber: 5, sceneStart: 0, sceneEnd: 3, effectStartLocalTime: 0.5, effectEndLocalTime: 2.5, leftEyeRegion: { x: 120, y: 75, width: 42, height: 26, space: "PIXELS" }, rightEyeRegion: { x: 180, y: 75, width: 42, height: 26, space: "PIXELS" }, leftHaloRegion: { x: 132, y: 80, width: 22, height: 16, space: "PIXELS" }, rightHaloRegion: { x: 192, y: 80, width: 22, height: 16, space: "PIXELS" }, leftPupilRegion: { x: 138, y: 82, width: 10, height: 12, space: "PIXELS" }, rightPupilRegion: { x: 198, y: 82, width: 10, height: 12, space: "PIXELS" }, featherAmount: 2, interpolation: "SMOOTHSTEP", blinkWindowsToPreserve: [{ startLocalTime: 1.2, endLocalTime: 1.4 }], ...overrides }; }
function haloRule(overrides: Partial<TroubleshootingRule> = {}): TroubleshootingRule { const source = VERIFIED_TROUBLESHOOTING_RULES.find(rule => rule.issueId === "GAZE_WHITE_HALO_COMPOSITING")!; return { ...source, autoRepairAllowed: true, verificationStatus: "VERIFIED", ...overrides }; }
function haloIncident(overrides: Record<string, unknown> = {}) { return incidentSchema.parse({ incidentId: "66666666-6666-4666-8666-666666666666", timestamp: "2026-09-15T00:00:00.000Z", projectId: "project-white-halo", sceneNumber: 5, stage: "POST_PROCESSING", component: "white-halo", symptoms: ["White halo around pupil"], errorMessages: ["GAZE_OVERLAY_COMPOSITING_FAIL"], errorCodes: ["GAZE_OVERLAY_COMPOSITING_FAIL"], firstDivergence: "GAZE_OVERLAY_COMPOSITING", expectedState: { halo: false }, actualState: haloState(), evidence: [{ kind: "halo-regions", source: "fixture", value: haloState() }], runtimeState: { generationStatus: "SUCCESS", outputReady: true }, checkpoint: { generationStatus: "SUCCESS", outputReady: true }, attemptCount: 0, previousRepairAttempts: [], affectedFiles: ["final.mp4"], preserveRequirements: ["Preserve approved Scene 1–4."], ...overrides }); }
function haloFinding(overrides: Partial<QaFinding> = {}): QaFinding { return { validatorId: "white-halo", status: "FAIL", sceneNumber: 5, globalTimestamp: 0.5, sceneLocalTimestamp: 0.5, expected: { halo: false }, actual: { halo: true }, evidence: ["fixture halo"], confidence: 1, severity: "HIGH", suggestedFirstDivergence: "GAZE_OVERLAY_COMPOSITING", affectedRegion: "eyes", affectedFile: "final.mp4", symptom: "White halo around pupil", ...overrides }; }
function coordinatorInput(currentVersion: Awaited<ReturnType<OutputVersionService["registerOriginalOutput"]>>, rule = haloRule(), incident = haloIncident(), finding = haloFinding()): PostAssemblyRepairInput { const match = matchIncidentToKnowledgeBase(incident, [rule]); return { projectId: "project-white-halo", qaRunId: "qa-halo-1", finding, incident, match, matchedRule: rule, currentOutputVersion: currentVersion, approvedManifest: { scenes: [1, 2, 3, 4, 5].map(sceneNumber => ({ sceneNumber, source: `scene-${sceneNumber}.mp4`, durationSec: 3 })) }, approvedSources: ["scene-1.mp4", "scene-2.mp4", "scene-3.mp4", "scene-4.mp4", "scene-5.mp4"], expectedSceneStates: {}, sceneMetadata: {}, checkpoint: { ...haloState(), generationStatus: "SUCCESS", outputReady: true }, preserveRequirements: ["Preserve approved Scene 1–4."], generationStatus: "SUCCESS", outputReady: true }; }
function failValidator(): QaValidator { return { id: "white-halo", validate: async () => [{ ...haloFinding(), status: "FAIL" }] }; }

describe("Reusable white-halo eye compositing handler", () => {
  it("CASE 1 creates candidate and runs for valid halo evidence", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new WhiteHaloValidator()]).repair(coordinatorInput(currentVersion)); expect(result.candidateVersionId).not.toBeNull(); expect(result.actionsTaken).toContain("renderLocalScleraWhiteHaloPatchToCandidate"); }); });
  it("CASE 2 removes white halo and validates all preservation checks", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new WhiteHaloValidator()]).repair(coordinatorInput(currentVersion)); const finding = result.validationResults.find(item => item.validatorId === "white-halo")?.findings[0]; expect(finding?.status).toBe("PASS"); expect(finding?.actual).toMatchObject({ WHITE_HALO_ABSENT: true, SCLERA_COLOR_MATCH: true, PUPIL_PRESERVED: true, GAZE_PRESERVED: true, EYE_SHAPE_PRESERVED: true, BLINK_PRESERVED: true, SMOKE_RING_PRESERVED: true, NO_HARD_PATCH_BOUNDARY: true }); }); });
  it("CASE 3 samples local sclera rather than fixed white", () => { const parameters = whiteHaloParametersSchema.parse({ ...haloState(), candidateInputPath: "in", candidateOutputPath: "out" }); const geometry = computeHaloGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 }); expect("error" in geometry).toBe(false); });
  it("CASE 4 uses anti-aliased patch edges", () => { const parameters = whiteHaloParametersSchema.parse({ ...haloState(), candidateInputPath: "in", candidateOutputPath: "out" }); const geometry = computeHaloGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 }); if ("error" in geometry) throw new Error(geometry.error); const frame = createWhiteHaloFrame(parameters, { width: 320, height: 180, fps: 10, duration: 3 }, 1, geometry, { left: { color: { r: 180, g: 198, b: 210 }, sampleCount: 20, maxDeviation: 0 }, right: { color: { r: 180, g: 198, b: 210 }, sampleCount: 20, maxDeviation: 0 } }); expect(frame[(88 * 320 + 133) * 4 + 3]).toBeGreaterThan(0); expect(frame[(80 * 320 + 132) * 4 + 3]).toBe(0); });
  it("CASE 5 preserves pupil position", () => { const parameters = whiteHaloParametersSchema.parse({ ...haloState(), candidateInputPath: "in", candidateOutputPath: "out" }); const geometry = computeHaloGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 }); if ("error" in geometry) throw new Error(geometry.error); const frame = createWhiteHaloFrame(parameters, { width: 320, height: 180, fps: 10, duration: 3 }, 1, geometry, { left: { color: { r: 1, g: 1, b: 1 }, sampleCount: 1, maxDeviation: 0 }, right: { color: { r: 1, g: 1, b: 1 }, sampleCount: 1, maxDeviation: 0 } }); expect(frame[(88 * 320 + 143) * 4 + 3]).toBe(0); });
  it("CASE 6 preserves pupil size/style", () => { expect(parseWhiteHaloParametersFromState(haloState(), 5, "in", "out")).toHaveProperty("value"); });
  it("CASE 7 preserves gaze", () => { const parsed = parseWhiteHaloParametersFromState(haloState(), 5, "in", "out"); expect("value" in parsed).toBe(true); });
  it("CASE 8 preserves blink window", () => { const parameters = whiteHaloParametersSchema.parse({ ...haloState(), candidateInputPath: "in", candidateOutputPath: "out" }); const geometry = computeHaloGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 }); if ("error" in geometry) throw new Error(geometry.error); expect(createWhiteHaloFrame(parameters, { width: 320, height: 180, fps: 10, duration: 3 }, 1.3, geometry, { left: null, right: null }).every(value => value === 0)).toBe(true); });
  it("CASE 9 preserves smoke-ring fixture", () => { const parameters = whiteHaloParametersSchema.parse({ ...haloState(), candidateInputPath: "in", candidateOutputPath: "out" }); const geometry = computeHaloGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 }); if ("error" in geometry) throw new Error(geometry.error); const frame = createWhiteHaloFrame(parameters, { width: 320, height: 180, fps: 10, duration: 3 }, 1, geometry, { left: { color: { r: 1, g: 1, b: 1 }, sampleCount: 1, maxDeviation: 0 }, right: { color: { r: 1, g: 1, b: 1 }, sampleCount: 1, maxDeviation: 0 } }); expect(frame[(130 * 320 + 160) * 4 + 3]).toBe(0); });
  it("CASE 10 limits changes to artifact FRAME_REGION", () => { const parameters = whiteHaloParametersSchema.parse({ ...haloState(), candidateInputPath: "in", candidateOutputPath: "out" }); const geometry = computeHaloGeometry(parameters, { width: 320, height: 180, fps: 10, duration: 3 }); if ("error" in geometry) throw new Error(geometry.error); const frame = createWhiteHaloFrame(parameters, { width: 320, height: 180, fps: 10, duration: 3 }, 1, geometry, { left: { color: { r: 1, g: 1, b: 1 }, sampleCount: 1, maxDeviation: 0 }, right: { color: { r: 1, g: 1, b: 1 }, sampleCount: 1, maxDeviation: 0 } }); expect(frame[(20 * 320 + 20) * 4 + 3]).toBe(0); });
  it("CASE 11 missing reliable sclera sample returns NEEDS_REVIEW", async () => { await withMediaDb(async ({ service, currentVersion }) => { const state = haloState({ leftHaloRegion: { x: 120, y: 75, width: 42, height: 26, space: "PIXELS" }, rightHaloRegion: { x: 180, y: 75, width: 42, height: 26, space: "PIXELS" } }); const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), []).repair(coordinatorInput(currentVersion, haloRule(), haloIncident({ actualState: state }))); expect(result.status).toBe("NEEDS_REVIEW"); expect(result.warnings).toContain("UNRELIABLE_SCLERA_SAMPLE"); }); });
  it("CASE 12 missing artifact region returns NEEDS_REVIEW", () => { expect(parseWhiteHaloParametersFromState(haloState({ leftHaloRegion: undefined, rightHaloRegion: undefined }), 5, "in", "out")).toEqual({ error: "MISSING_HALO_REGION" }); });
  it("CASE 13 ambiguous characters are not guessed", () => { expect(parseWhiteHaloParametersFromState(haloState({ multipleCharacters: true }), 5, "in", "out")).toEqual({ error: "AMBIGUOUS_HALO_TARGET" }); });
  it("CASE 14 double pupil is not repaired by halo handler", () => { expect(parseWhiteHaloParametersFromState(haloState({ doublePupilPresent: true }), 5, "in", "out")).toEqual({ error: "INDEPENDENT_DOUBLE_PUPIL_PRESENT" }); });
  it("CASE 15 promotes candidate after validation PASS", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new WhiteHaloValidator()]).repair(coordinatorInput(currentVersion)); expect(result.status).toBe("PROMOTED"); }); });
  it("CASE 16 validation FAIL rejects candidate and keeps CURRENT", async () => { await withMediaDb(async ({ service, currentVersion }) => { const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [failValidator()]).repair(coordinatorInput(currentVersion)); expect(result.status).toBe("REPAIR_FAILED"); expect((await service.getCurrentOutput("project-white-halo"))?.id).toBe(currentVersion.id); }); });
  it("CASE 17 handler never writes CURRENT directly", async () => { await withMediaDb(async ({ service, currentVersion }) => { const before = await readFile(currentVersion.filePath); const candidate = await service.createCandidate({ projectId: "project-white-halo", sourcePath: currentVersion.filePath, currentVersionId: currentVersion.id }); const result = await createWhiteHaloPostAssemblyHandler().handlePostAssembly({ incident: haloIncident(), rule: haloRule(), candidateVersionId: candidate.id, candidatePath: candidate.filePath, currentOutputPath: currentVersion.filePath, repairAttemptId: "attempt" }); expect(result.filesChanged).toEqual([candidate.filePath]); expect(await readFile(currentVersion.filePath)).toEqual(before); }); });
  it("CASE 18 handler throw rejects candidate and creates report/handoff", async () => { await withMediaDb(async ({ service, currentVersion }) => { const throwing: PostAssemblyRepairHandler = { ...createWhiteHaloPostAssemblyHandler(), handlePostAssembly: async () => { throw new Error("halo handler exploded"); } }; const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry([throwing]), [], async () => ({ jsonReportPath: "json", markdownReportPath: "md" })).repair(coordinatorInput(currentVersion)); expect(result.status).toBe("REPAIR_FAILED"); expect(result.rejectedCandidateId).toBe(result.candidateVersionId); expect(result.codexHandoffText).toContain("CODEX HANDOFF"); }); });
  it("CASE 19 same input and parameters produce deterministic output", async () => { await withMediaDb(async ({ ffmpegPath, root, currentVersion }) => { const firstPath = path.join(root, "halo-1.mp4"); const secondPath = path.join(root, "halo-2.mp4"); const first = whiteHaloParametersSchema.parse({ ...haloState(), candidateInputPath: currentVersion.filePath, candidateOutputPath: firstPath }); await renderWhiteHaloCandidate(first, ffmpegPath); await renderWhiteHaloCandidate({ ...first, candidateOutputPath: secondPath }, ffmpegPath); expect(await hashOutputFile(firstPath)).toBe(await hashOutputFile(secondPath)); }); });
  it("CASE 20 retry limit prevents loop", async () => { await withMediaDb(async ({ service, currentVersion }) => { let calls = 0; const handler: PostAssemblyRepairHandler = { ...createWhiteHaloPostAssemblyHandler(), handlePostAssembly: async () => { calls += 1; throw new Error("must not run"); } }; const result = await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry([handler]), []).repair(coordinatorInput(currentVersion, haloRule(), haloIncident({ previousRepairAttempts: [{ ruleId: "GAZE_WHITE_HALO_COMPOSITING", status: "REPAIR_FAILED", at: "2026-09-15T00:00:00.000Z" }] }))); expect(result.status).toBe("RETRY_LIMIT_REACHED"); expect(calls).toBe(0); }); });
  it("CASE 21 preserves generationStatus SUCCESS", async () => { await withMediaDb(async ({ service, currentVersion }) => { expect((await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new WhiteHaloValidator()]).repair(coordinatorInput(currentVersion))).generationStatus).toBe("SUCCESS"); }); });
  it("CASE 22 preserves outputReady true", async () => { await withMediaDb(async ({ service, currentVersion }) => { expect((await new PostAssemblyRepairCoordinator(service, new RepairHandlerRegistry(), [new WhiteHaloValidator()]).repair(coordinatorInput(currentVersion))).outputReady).toBe(true); }); });
  it("CASE 23 production registry contains white-halo handler", () => { expect(new RepairHandlerRegistry().getPostAssembly("GAZE_WHITE_HALO_COMPOSITING")?.postAssembly).toMatchObject({ handlerId: WHITE_HALO_HANDLER_ID, handlerVersion: WHITE_HALO_HANDLER_VERSION, supportsPostAssembly: true, repairScope: "FRAME_REGION", mutatesOutputFile: true, requiresCandidate: true }); });
  it("CASE 24 keeps white-halo handler registered", () => { expect(new RepairHandlerRegistry().getPostAssembly("GAZE_WHITE_HALO_COMPOSITING")).toBeDefined(); });
  it("CASE 25 blocks unproven white-halo auto repair", () => { expect(VERIFIED_TROUBLESHOOTING_RULES.find(rule => rule.issueId === "GAZE_WHITE_HALO_COMPOSITING")?.autoRepairAllowed).toBe(false); });
});
