import { describe, expect, it } from "vitest";
import { selectCharacterReferences, buildCharacterIdentityInstruction, type CharacterIdentityPackSummary } from "@/modules/channels/identity-pack";
import { assertCharacterIdentityPackReady, characterIdentityPackSchema, identityGenerationGate, validateCharacterIdentity, type CharacterIdentityPack } from "./character-identity";

const pack = (overrides: Partial<CharacterIdentityPack> = {}): CharacterIdentityPack => characterIdentityPackSchema.parse({ characterId: "character-1", channelId: "channel-1", name: "Main Character", styleType: "3D", referenceImages: [{ assetId: "asset-front", storageKey: "channel-1.png", viewRole: "front", active: true, referenceId: null }], lockedTraits: { faceIdentity: "round face", facialStructure: "small nose", skinTone: "warm", baseHairstyle: "short black hair", bodyProportions: "compact", bodyBuild: "slim", ageAppearance: "adult", distinctiveTraits: "left cheek mark", coreCharacterDesignLanguage: "stylized 3D" }, allowedVariations: ["clothing", "emotion", "pose"], negativeRules: ["Never replace the main character."], active: true, ...overrides });
const displayPack = (value = pack()): CharacterIdentityPackSummary => ({ ...value, referenceImages: value.referenceImages.map(reference => ({ ...reference, referenceId: reference.referenceId ?? null, name: null, mimeType: "image/png", url: `/api/v1/channels/${value.channelId}/character-image?assetId=${reference.assetId}` })) });

describe("STEP 1 Channel Character Identity Lock", () => {
  it("CASE 1 accepts one active Character Identity Pack with reference assets", () => { const result = characterIdentityPackSchema.parse(pack()); expect(result.channelId).toBe("channel-1"); expect(result.referenceImages).toHaveLength(1); expect(result.referenceImages[0].viewRole).toBe("front"); });
  it("CASE 2 missing pack cannot pass the generation gate", () => { expect(() => assertCharacterIdentityPackReady(null)).toThrow("MAIN_CHARACTER_IDENTITY_MISSING"); });
  it("CASE 3 scene outfit variation does not fail locked identity", () => { const result = validateCharacterIdentity({ lockedTraits: pack().lockedTraits, actualIdentity: pack().lockedTraits, actualStyleType: "3D", sceneAppearance: { outfit: "protective suit", accessories: ["glasses"] } }); expect(result.status).toBe("PASS"); expect(result.checks.BASE_STYLE ?? result.checks.CORE_STYLE_MATCH).toBeTruthy(); });
  it("CASE 4 face or body drift fails CHARACTER_IDENTITY_MATCH", () => { const actual = { ...pack().lockedTraits, faceIdentity: "different face", bodyBuild: "different build" }; const result = validateCharacterIdentity({ lockedTraits: pack().lockedTraits, actualIdentity: actual, actualStyleType: "3D" }); expect(result.status).toBe("FAIL"); expect(result.issues).toEqual(expect.arrayContaining(["faceIdentity_FAIL", "bodyBuild_FAIL"])); expect(identityGenerationGate(result)).toBe("BLOCK"); });
  it("CASE 5 selects exact view role and falls back to compatible references", () => { const references = [{ assetId: "front", storageKey: "front.png", viewRole: "front", active: true, referenceId: null }, { assetId: "profile", storageKey: "profile.png", viewRole: "left_profile", active: true, referenceId: null }]; const current = displayPack(pack({ referenceImages: references })); expect(selectCharacterReferences(current, "left_profile").map(reference => reference.assetId)).toEqual(["profile"]); expect(selectCharacterReferences(current, "right_profile").map(reference => reference.assetId)).toEqual(["front", "profile"]); });
  it("CASE 6 identity mismatch blocks scene video continuation", () => { const result = validateCharacterIdentity({ lockedTraits: pack().lockedTraits, actualIdentity: { ...pack().lockedTraits, coreCharacterDesignLanguage: "unrelated" }, actualStyleType: "3D" }); expect(identityGenerationGate(result)).toBe("BLOCK"); });
  it("CASE 7 missing visual evidence becomes NEEDS_REVIEW, never fake PASS", () => { const result = validateCharacterIdentity({ lockedTraits: pack().lockedTraits, actualIdentity: null, actualStyleType: null }); expect(result.status).toBe("NOT_EVALUATED"); expect(identityGenerationGate(result)).toBe("NEEDS_REVIEW"); });
  it("CASE 8 prompt injection separates PRESERVE IDENTITY and APPLY SCENE APPEARANCE", () => { const prompt = buildCharacterIdentityInstruction(displayPack()); expect(prompt).toContain("PRESERVE IDENTITY"); expect(prompt).toContain("APPLY SCENE APPEARANCE"); expect(prompt).toContain("Never replace the main character."); });
  it("CASE 9 inactive pack/reference is rejected before generation", () => {
    expect(() => assertCharacterIdentityPackReady(pack({ active: false }))).toThrow("MAIN_CHARACTER_IDENTITY_MISSING");
    expect(() => assertCharacterIdentityPackReady(pack({ referenceImages: [{ ...pack().referenceImages[0], active: false }] }))).toThrow("MAIN_CHARACTER_IDENTITY_MISSING");
  });
  it("CASE 10 only one active main pack is representable per channel", () => { expect(() => characterIdentityPackSchema.parse({ ...pack(), channelId: "", characterId: "" })).toThrow(); expect(pack().channelId).toBe("channel-1"); });
});
