ALTER TABLE "CodexJob" ADD COLUMN "generationStatus" TEXT NOT NULL DEFAULT 'RUNNING';
ALTER TABLE "CodexJob" ADD COLUMN "qualityStatus" TEXT NOT NULL DEFAULT 'NOT_RUN';
ALTER TABLE "CodexJob" ADD COLUMN "outputReady" BOOLEAN NOT NULL DEFAULT false;
