import { type TroubleshootingRule, validateTroubleshootingRules } from "./schema";

export const TROUBLESHOOTING_KNOWLEDGE_BASE_KEY = "official-troubleshooting";
export const TROUBLESHOOTING_KNOWLEDGE_BASE_VERSION = "1.5.0";
export const TROUBLESHOOTING_LAST_VERIFIED_AT = "2026-09-14";

const boundedRetry = (maxAttempts = 1) => ({
  maxAttempts,
  backoff: maxAttempts ? { strategy: "EXPONENTIAL" as const, baseDelayMs: 1_000, maxDelayMs: 30_000 } : { strategy: "NONE" as const, baseDelayMs: 0, maxDelayMs: 0 },
  stopConditions: ["Dừng khi có bằng chứng divergence nằm ngoài phạm vi rule.", maxAttempts ? "Dừng khi hết maxAttempts; giữ checkpoint và escalates sang kiểm tra thủ công." : "Không retry tự động; cần kiểm tra thủ công có evidence."],
});

const AUTO_SAFE_RULE_IDS = new Set(["FALLBACK_DOWNLOAD_ERROR_PROPAGATION", "LOW_CREDIT_FALSE_BLOCK"]);
const AUTO_GUARDED_RULE_IDS = new Set(["ELECTRON_FLOW_FETCH_TIMEOUT_FALLBACK", "FLOW_SMOKE_RING_OMITTED", "BLINK_DOES_NOT_REOPEN", "GAZE_NOT_TO_MONITOR", "GAZE_WHITE_HALO_COMPOSITING", "DOUBLE_PUPIL_ERASURE_ALIGNMENT", "FLOW_READABLE_TEXT_OUTPUT"]);
const MANUAL_ONLY_RULE_IDS = new Set(["EXTERNAL_EXECUTION_POLICY_MANUAL_HANDOFF"]);

export const AUTO_REPAIR_RULE_POLICY = { AUTO_SAFE_RULE_IDS, AUTO_GUARDED_RULE_IDS, MANUAL_ONLY_RULE_IDS };

// Evidence catalog is deliberately empty: no reviewed incident proves repair,
// post-repair validation AND successful production resume. Rule text is not evidence.
export const PRODUCTION_REPAIR_PROVENANCE: readonly {
  ruleId: string; runId: string; incidentId: string; fingerprint: string;
  firstDivergence: string; rootCause: string; repairExecutionRef: string;
  validationRef: string; successfulOutputRef: string; diagnosticRef: string;
}[] = [];

export function hasProductionRepairProvenance(rule: TroubleshootingRule) {
  return PRODUCTION_REPAIR_PROVENANCE.some(entry => entry.ruleId === rule.issueId &&
    entry.firstDivergence === rule.firstDivergence && entry.rootCause === rule.rootCause &&
    [entry.runId, entry.incidentId, entry.fingerprint, entry.repairExecutionRef, entry.validationRef, entry.successfulOutputRef, entry.diagnosticRef].every(value => value.trim().length > 0));
}

export const AUTO_REPAIR_PROVENANCE_REVIEWS = [...AUTO_SAFE_RULE_IDS, ...AUTO_GUARDED_RULE_IDS].map(ruleId => ({
  ruleId, provenanceClassification: "TEST_PROVEN_ONLY" as const,
  evidencePresent: false,
  decisionReason: "Không tìm thấy chuỗi production incident → repair execution → post-repair validation → successful resume/output; fixture và nhãn VERIFIED không đủ.",
}));

type PartialRule = Omit<TroubleshootingRule, "version" | "verificationStatus" | "autoRepairAllowed" | "automationClass" | "confidenceThreshold" | "lastVerifiedAt" | "retryPolicy" | "severity" | "preconditions" | "fallback" | "preserveRequirements"> & Partial<Pick<TroubleshootingRule, "retryPolicy" | "severity" | "preconditions" | "fallback" | "preserveRequirements">>;

function verified(input: PartialRule): TroubleshootingRule {
  return {
    version: TROUBLESHOOTING_KNOWLEDGE_BASE_VERSION,
    verificationStatus: AUTO_SAFE_RULE_IDS.has(input.issueId) || AUTO_GUARDED_RULE_IDS.has(input.issueId) ? "PROVISIONAL" : "VERIFIED",
    autoRepairAllowed: false,
    automationClass: AUTO_SAFE_RULE_IDS.has(input.issueId) ? "AUTO_SAFE" : AUTO_GUARDED_RULE_IDS.has(input.issueId) ? "AUTO_GUARDED" : MANUAL_ONLY_RULE_IDS.has(input.issueId) ? "MANUAL_ONLY" : "NO_HANDLER_YET",
    confidenceThreshold: 0.9,
    lastVerifiedAt: AUTO_SAFE_RULE_IDS.has(input.issueId) || AUTO_GUARDED_RULE_IDS.has(input.issueId) ? null : TROUBLESHOOTING_LAST_VERIFIED_AT,
    retryPolicy: boundedRetry(),
    severity: "HIGH",
    preconditions: ["Có evidence của incident và không thay đổi pipeline trong lúc chẩn đoán."],
    fallback: "Giữ checkpoint, báo trạng thái và chuyển sang kiểm tra thủ công có evidence.",
    preserveRequirements: ["Không thay đổi asset/video approved hoặc các phần đã PASS."],
    ...input,
    ...(AUTO_SAFE_RULE_IDS.has(input.issueId) || AUTO_GUARDED_RULE_IDS.has(input.issueId) ? { tags: [...input.tags, "production-provenance-unconfirmed"] } : {}),
  };
}

const rules: TroubleshootingRule[] = [
  verified({ issueId: "FLOW_REFERENCE_MEDIAID_POPUP_BINDING", title: "Flow popup không bind reference theo mediaId", description: "Popup thư viện Flow không hiển thị UUID mediaId trực tiếp nên selector theo UUID không thể xác minh attachment.", stage: "FLOW_RUNTIME", symptoms: ["Chọn reference nhưng composer không có chip đúng asset."], errorSignatures: ["FLOW_REFERENCE_BINDING_FAILED", "mediaId absent in popup"], firstDivergence: "FLOW_RUNTIME", rootCause: "Popup chỉ hiển thị thumbnail/token nội bộ, không chứa UUID mediaId.", optimalFix: "Map mediaId → outside-library asset → asb token → popup thumbnail; chọn thumbnail và xác minh chip /image/<mediaId>.", doNotDo: ["Không coi click popup là thành công nếu chưa thấy chip đúng identity.", "Không đoán thumbnail chỉ bằng vị trí."], validationAfterFix: ["Composer có chip /image/<mediaId> đúng asset.", "Prompt/attachment identity được lưu trong checkpoint."], repairScope: "REFERENCE", tags: ["flow", "reference", "media-id"], evidenceRequired: ["mediaId", "outside-library asset", "asb token", "composer chip sau attach"], affectedComponents: ["electron/main.cjs", "Flow composer"], createdFromIncident: "Flow reference attachment verified incident" }),
  verified({ issueId: "MEDIAID_PIPELINE_PERSISTENCE", title: "mediaId không được giữ xuyên pipeline/build", description: "Reference identity bị mất giữa các bước nên runtime không thể bind hoặc xác minh đúng asset.", stage: "REFERENCE", symptoms: ["Build/runtime không còn mediaId để attach reference."], errorSignatures: ["MEDIA_ID_MISSING", "REFERENCE_IDENTITY_LOST"], firstDivergence: "CHECKPOINT", rootCause: "mediaId không được persist xuyên các DTO/checkpoint.", optimalFix: "Persist mediaId trong asset mapping, job payload, checkpoint và dữ liệu build cần thiết.", doNotDo: ["Không thay bằng filename hoặc URL mơ hồ."], validationAfterFix: ["mediaId còn nguyên sau restart/resume.", "Attachment được xác minh bằng mediaId."], repairScope: "CHECKPOINT", tags: ["media-id", "persistence", "reference"], evidenceRequired: ["Payload trước/sau pipeline", "checkpoint/resume record"], affectedComponents: ["asset mapping", "checkpoint"], createdFromIncident: "Reference persistence incident" }),
  verified({ issueId: "ELECTRON_FLOW_FETCH_TIMEOUT_FALLBACK", title: "Electron session.fetch tải Flow asset bị treo", description: "Lệnh tải asset qua Electron session.fetch có thể không resolve khiến Flow runtime bị kẹt.", stage: "DOWNLOAD", symptoms: ["Download không hoàn thành dù Flow đã có asset."], errorSignatures: ["FLOW_ASSET_DOWNLOAD_TIMEOUT", "session.fetch pending"], firstDivergence: "DOWNLOAD", rootCause: "session.fetch không có timeout hữu hạn và có đường treo theo session.", optimalFix: "Dùng finite timeout; khi hết thời gian, tải fallback trong page context rồi kiểm tra file cuối.", doNotDo: ["Không chờ fetch vô hạn.", "Không coi primary error là FAIL khi fallback và validation cuối PASS."], validationAfterFix: ["File local tồn tại, đủ kích thước và giải mã được.", "Checkpoint ghi recovered warning nếu fallback đã dùng."], repairScope: "DOWNLOAD", tags: ["electron", "download", "fallback"], evidenceRequired: ["Timeout evidence", "fallback source", "file validation"], affectedComponents: ["electron/main.cjs", "download bridge"], createdFromIncident: "Flow asset download recovery incident" }),
  verified({ issueId: "EXPECTED_STATE_START_ACTION_CONFLICT", title: "Expected State trộn start state và future action", description: "Một start-frame không thể vừa là trạng thái ban đầu vừa chứa hành động xảy ra sau đó.", stage: "PROJECT", symptoms: ["Start frame sai pose hoặc validator báo mâu thuẫn action."], errorSignatures: ["EXPECTED_STATE_CONTRADICTION"], firstDivergence: "EXPECTED_STATE", rootCause: "Expected State không tách START_FRAME_STATE khỏi ACTION_STATE.", optimalFix: "Tách riêng start state bất động và action timeline/future state.", doNotDo: ["Không nhét future action vào prompt start frame."], validationAfterFix: ["Start-frame prompt chỉ mô tả initial state.", "Action state được giữ trong video/action prompt."], repairScope: "PROMPT", tags: ["expected-state", "start-frame", "prompt"], evidenceRequired: ["Expected State", "start-frame prompt", "action prompt"], affectedComponents: ["expected state builder", "prompt compiler"], createdFromIncident: "Expected State conflict incident" }),
  verified({ issueId: "SCENE_TEXT_POLICY_CONTRADICTION", title: "Scene text contradiction", description: "Rule global no-text xung đột với chữ bắt buộc của scene.", stage: "PROMPT", symptoms: ["Prompt tự mâu thuẫn hoặc text bị loại sai."], errorSignatures: ["TEXT_POLICY_CONTRADICTION"], firstDivergence: "PROMPT", rootCause: "Không có policy text theo scene.", optimalFix: "Dùng REQUIRED_TEXT, ALLOWED_TEXT và FORBIDDEN_TEXT theo từng scene.", doNotDo: ["Không áp dụng global no-text để xóa required text hợp lệ."], validationAfterFix: ["Prompt không mâu thuẫn.", "Validator biết text nào được phép/chính xác."], repairScope: "PROMPT", tags: ["text", "prompt", "policy"], evidenceRequired: ["Scene expected text", "compiled prompt", "validator result"], affectedComponents: ["prompt compiler", "validator"], createdFromIncident: "Scene text policy incident" }),
  verified({ issueId: "DIRTY_BACKGROUND_REFERENCE_TEXT", title: "Unwanted text từ dirty background reference", description: "Reference bối cảnh có chữ làm model tái tạo chữ dù scene cấm text.", stage: "REFERENCE", symptoms: ["Readable text xuất hiện trong video/ảnh dù prompt cấm."], errorSignatures: ["UNWANTED_READABLE_TEXT"], firstDivergence: "BACKGROUND_REFERENCE", rootCause: "Background reference chứa text/logo bẩn.", optimalFix: "Thay bằng clean background reference đã kiểm tra no-text.", doNotDo: ["Không regenerate nhiều lần bằng cùng dirty background."], validationAfterFix: ["Reference sạch chữ.", "Output không có readable text ở các mốc kiểm tra."], repairScope: "REFERENCE", tags: ["background", "text", "reference"], evidenceRequired: ["Reference frame", "output frame", "text validation"], affectedComponents: ["background assets", "asset validator"], createdFromIncident: "Scene 5 clean-background incident" }),
  verified({ issueId: "FALSE_BLACK_OUTPUT_DIAGNOSIS", title: "Chẩn đoán nhầm black output", description: "Output trông đen có thể do tải/preview/brightness thay vì generation hỏng.", stage: "DOWNLOAD", symptoms: ["Preview hoặc frame check có màu đen."], errorSignatures: ["BLACK_OUTPUT_SUSPECTED"], firstDivergence: "DOWNLOAD", rootCause: "Kết luận từ preview đơn lẻ trước khi kiểm tra source Flow, file local và brightness.", optimalFix: "Kiểm tra Flow asset, file local, metadata và brightness trước quyết định regenerate.", doNotDo: ["Không regenerate chỉ dựa trên preview tối."], validationAfterFix: ["Có evidence source/file/brightness.", "Chỉ regenerate khi source thực sự invalid."], repairScope: "DOWNLOAD", tags: ["diagnosis", "black-output", "download"], evidenceRequired: ["Flow asset", "local file", "brightness/frame metadata"], affectedComponents: ["download validation", "media inspection"], createdFromIncident: "Black-output false diagnosis incident" }),
  verified({ issueId: "START_FRAME_GAZE_CONSTRAINT", title: "Start-frame gaze sai", description: "Mắt nhân vật không hướng theo yêu cầu scene khi prompt thiếu ràng buộc rõ và không validate output.", stage: "ASSETS", symptoms: ["Nhân vật nhìn thẳng thay vì nhìn mục tiêu."], errorSignatures: ["START_FRAME_GAZE_MISMATCH"], firstDivergence: "PROMPT", rootCause: "Gaze chỉ được mô tả ngầm.", optimalFix: "Thêm gaze constraint rõ ràng theo target và validate ngay output start frame.", doNotDo: ["Không chuyển sang video khi start-frame gaze chưa đạt."], validationAfterFix: ["Gaze target đạt trong start frame."], repairScope: "PROMPT", tags: ["gaze", "start-frame", "validation"], evidenceRequired: ["Start-frame prompt", "start-frame output"], affectedComponents: ["prompt compiler", "asset validator"], createdFromIncident: "Start-frame gaze incident" }),
  verified({ issueId: "SCENE_ONE_ACTION_BEAT_OVERLOAD", title: "Scene 1 có quá nhiều action beats", description: "Một clip ngắn không ổn định khi prompt yêu cầu quá nhiều hành động nối tiếp.", stage: "SCENES", symptoms: ["Motion lộn xộn hoặc end state sai."], errorSignatures: ["ACTION_BEAT_OVERLOAD"], firstDivergence: "PROMPT", rootCause: "Prompt không có ordered timeline và end-state lock.", optimalFix: "Giảm action beats, viết timeline có thứ tự và khóa end state.", doNotDo: ["Không nhồi nhiều beat đồng thời vào scene ngắn."], validationAfterFix: ["Action theo đúng thứ tự.", "End state khớp expected state."], repairScope: "PROMPT", tags: ["scene-1", "motion", "prompt"], evidenceRequired: ["Video prompt", "timeline", "end-state validation"], affectedComponents: ["scene prompt compiler"], createdFromIncident: "Scene 1 action overload incident" }),
  verified({ issueId: "FLOW_KEYBOARD_ACTION_UNREALIZED", title: "Flow không thực hiện keyboard action dù prompt đúng", description: "Provider bỏ qua action đặc thù dù prompt đã PASS.", stage: "SCENES", symptoms: ["Không có thao tác bàn phím trong output."], errorSignatures: ["KEYBOARD_ACTION_MISSING"], firstDivergence: "FLOW_VIDEO_OUTPUT", rootCause: "Khả năng thực thi action của Flow không ổn định cho beat phức tạp.", optimalFix: "Đơn giản hóa hoặc tách action thành clip/segment đáng tin cậy.", doNotDo: ["Không tiếp tục sửa prompt khi prompt đã PASS và divergence là Flow output."], validationAfterFix: ["Output thực hiện action hoặc segment replacement đã được validate."], repairScope: "SCENE", tags: ["flow", "keyboard", "action"], evidenceRequired: ["Approved prompt", "output validation"], affectedComponents: ["scene generation"], createdFromIncident: "Keyboard action Flow incident" }),
  verified({ issueId: "UNSTABLE_SEGMENT_MOTION_HANDOFF", title: "Segment motion không ổn định", description: "Một đoạn chuyển động không đạt sau thử nghiệm provider nên không nên kéo toàn pipeline theo nó.", stage: "SCENES", symptoms: ["Motion segment không reliable hoặc continuity gãy."], errorSignatures: ["SEGMENT_MOTION_UNSTABLE"], firstDivergence: "FLOW_VIDEO_OUTPUT", rootCause: "Provider không tạo reliable motion segment.", optimalFix: "Dùng approved static handoff frame, hard cut và segment đã chứng minh reliable.", doNotDo: ["Không regenerate toàn bộ scene chỉ vì một segment."], validationAfterFix: ["Handoff frame approved.", "Hard cut/segment continuity hợp lệ."], repairScope: "SCENE", tags: ["segment", "handoff", "continuity"], evidenceRequired: ["Reliable segment", "approved handoff frame"], affectedComponents: ["scene editing", "assembly plan"], createdFromIncident: "Segment reliability incident" }),
  verified({ issueId: "FLOW_NINE_BY_SIXTEEN_CONTROL_LIFECYCLE", title: "Flow 9:16 control không tìm thấy", description: "Automation tìm settings ở CDP target/lifecycle cũ nên không thấy control thật.", stage: "FLOW_RUNTIME", symptoms: ["Không chọn được 9:16."], errorSignatures: ["FLOW_ASPECT_RATIO_CONTROL_MISSING"], firstDivergence: "FLOW_RUNTIME", rootCause: "Settings DOM chưa sẵn sàng hoặc dùng sai current CDP target.", optimalFix: "Chờ actual settings DOM, dùng current CDP target và verify radio 9:16.", doNotDo: ["Không giả định control đã chọn từ text cũ hoặc target cũ."], validationAfterFix: ["Radio 9:16 được selected trong DOM hiện tại."], repairScope: "FLOW_RUNTIME", tags: ["flow", "settings", "9-16", "cdp"], evidenceRequired: ["Current target URL", "settings DOM", "radio state"], affectedComponents: ["electron/main.cjs", "CDP automation"], createdFromIncident: "Flow 9:16 lifecycle incident" }),
  verified({ issueId: "START_FRAME_ATTACHMENT_SELECTOR_STALE", title: "Selector xác minh start-frame đã cũ", description: "Selector cũ không phản ánh composer/add-ingredients DOM hiện tại.", stage: "COMPOSER", symptoms: ["Attachment bị báo thiếu dù asset đã chọn hoặc ngược lại."], errorSignatures: ["START_FRAME_ATTACHMENT_NOT_VERIFIED"], firstDivergence: "COMPOSER", rootCause: "DOM Flow thay đổi.", optimalFix: "Dùng current composer/add-ingredients DOM và verify actual asset identity.", doNotDo: ["Không xác minh bằng selector legacy hoặc filename mơ hồ."], validationAfterFix: ["Composer hiển thị asset identity đúng."], repairScope: "FLOW_RUNTIME", tags: ["composer", "selector", "attachment"], evidenceRequired: ["Current DOM snapshot", "asset identity"], affectedComponents: ["electron/main.cjs"], createdFromIncident: "Start-frame selector incident" }),
  verified({ issueId: "EXTERNAL_EXECUTION_POLICY_MANUAL_HANDOFF", title: "External execution policy chặn Generate", description: "Policy ngăn auto Generate; cố bypass sẽ làm mất kiểm soát và checkpoint.", stage: "FLOW_RUNTIME", symptoms: ["Generate phải chờ thao tác thủ công hợp lệ."], errorSignatures: ["EXTERNAL_EXECUTION_POLICY_BLOCKED"], firstDivergence: "FLOW_RUNTIME", rootCause: "Giới hạn policy external execution.", optimalFix: "Tạo persistent manual handoff checkpoint và resume có xác minh sau thao tác thủ công.", doNotDo: ["Không bypass policy.", "Không mất prompt/start frame khi handoff."], retryPolicy: boundedRetry(0), validationAfterFix: ["Checkpoint tồn tại qua restart.", "Resume chỉ thành công khi asset cuối được validate."], repairScope: "CHECKPOINT", tags: ["policy", "manual-handoff", "checkpoint"], evidenceRequired: ["Policy block", "checkpoint", "resume validation"], affectedComponents: ["electron checkpoint storage"], createdFromIncident: "Manual Flow handoff incident" }),
  verified({ issueId: "FALLBACK_DOWNLOAD_ERROR_PROPAGATION", title: "Resume báo FAIL dù fallback download thành công", description: "Primary error vẫn được propagate sau khi fallback đã tải file và final validation PASS.", stage: "DOWNLOAD", symptoms: ["Resume FAIL nhưng file cuối hợp lệ."], errorSignatures: ["FALLBACK_SUCCESS_REPORTED_AS_FAILURE"], firstDivergence: "DOWNLOAD", rootCause: "Error propagation không chuyển primary failure thành recovered warning.", optimalFix: "Khi fallback + final validation PASS, lưu RECOVERED_WARNING và trả success.", doNotDo: ["Không che primary error; giữ nó trong warning/checkpoint."], validationAfterFix: ["File validated.", "Checkpoint status COMPLETED và có recovered warning."], repairScope: "DOWNLOAD", tags: ["fallback", "download", "checkpoint"], evidenceRequired: ["Primary error", "fallback result", "file validation"], affectedComponents: ["electron/manual-flow checkpoint"], createdFromIncident: "Fallback resume incident" }),
  verified({ issueId: "COMPOSER_STATE_SESSION_LIFECYCLE", title: "Composer mất prompt/start-frame giữa runtime sessions", description: "Composer state tồn tại trong DOM và mất khi page/runtime thay đổi.", stage: "COMPOSER", symptoms: ["Prompt rỗng, attachment chip biến mất, Generate disabled."], errorSignatures: ["COMPOSER_STATE_LOST", "GENERATE_DISABLED"], firstDivergence: "COMPOSER_STATE_LIFECYCLE", rootCause: "Runtime/session lifecycle không giữ DOM composer state.", optimalFix: "Rehydrate project, attachment và prompt ngay trước Generate.", doNotDo: ["Không tách Prepare và Generate sang runtime khác mà không rehydrate."], validationAfterFix: ["Prompt tồn tại.", "Attachment đúng.", "Generate enabled ngay trước click."], repairScope: "CHECKPOINT", tags: ["composer", "rehydrate", "lifecycle"], evidenceRequired: ["Before/after DOM", "checkpoint payload"], affectedComponents: ["electron/main.cjs", "manual checkpoint"], createdFromIncident: "Composer lifecycle incident" }),
  verified({ issueId: "LOW_CREDIT_FALSE_BLOCK", title: "Running low on credits không phải credit block", description: "Cảnh báo low credit bị diễn giải nhầm là yêu cầu bị từ chối.", stage: "FLOW_RUNTIME", symptoms: ["Automation dừng chỉ vì cảnh báo low credits."], errorSignatures: ["RUNNING_LOW_ON_CREDITS"], firstDivergence: "FLOW_RUNTIME", rootCause: "Thiếu bằng chứng direct credit rejection.", optimalFix: "Chỉ xác nhận CREDIT_BLOCK khi có insufficient credits, zero credits, quota exceeded hoặc rejected request.", doNotDo: ["Không kết luận hết credit từ 'running low'."], validationAfterFix: ["Log/UI có direct evidence nếu kết luận credit block."], repairScope: "FLOW_RUNTIME", tags: ["credits", "diagnosis", "flow"], evidenceRequired: ["Exact provider message", "request result"], affectedComponents: ["Flow status classifier"], createdFromIncident: "Low-credit diagnosis incident" }),
  verified({ issueId: "PRE_GENERATE_COMPOSER_NOT_READY", title: "Generate không tạo job vì composer chưa ready", description: "Click Generate không gửi job nếu composer bị mất trạng thái sẵn sàng.", stage: "COMPOSER", symptoms: ["Không có request/job sau click Generate."], errorSignatures: ["FLOW_JOB_NOT_CREATED", "PRE_GENERATE_STATE_INVALID"], firstDivergence: "PRE_GENERATE_STATE", rootCause: "Composer lifecycle mất prompt hoặc attachment trước click.", optimalFix: "Rehydrate và Generate trong cùng runtime sau khi xác minh READY.", doNotDo: ["Không click Generate lặp vô hạn khi READY chưa PASS."], validationAfterFix: ["READY_TO_GENERATE PASS.", "Request/job được tạo sau đúng một click."], repairScope: "CHECKPOINT", tags: ["generate", "composer", "ready"], evidenceRequired: ["Composer readiness", "network/job evidence"], affectedComponents: ["electron/main.cjs"], createdFromIncident: "Pre-generate readiness incident" }),
  verified({ issueId: "FLOW_AUDIO_GENERATION_FAILED", title: "Flow Audio generation failed", description: "Flow tạo job nhưng thất bại trong generation execution ở audio stage.", stage: "SCENES", symptoms: ["Flow card Failed: Audio generation failed."], errorSignatures: ["Audio generation failed"], firstDivergence: "GENERATION_EXECUTION", rootCause: "Audio stage provider fail sau job creation, không phải credit block.", optimalFix: "Bỏ audio request và tạo visual-only đúng một lần theo checkpoint.", doNotDo: ["Không đổi model/config ngoài phạm vi.", "Không thử prompt khác lặp lại."], validationAfterFix: ["Audio request removed.", "Video visual-only tải và giải mã được."], repairScope: "PROMPT", tags: ["flow", "audio", "generation"], evidenceRequired: ["HTTP/job evidence", "exact provider error"], affectedComponents: ["scene prompt", "Flow generation"], createdFromIncident: "Scene 5 audio failure incident" }),
  verified({ issueId: "FLOW_READABLE_TEXT_OUTPUT", title: "Flow render readable text sai vị trí", description: "Provider tự tạo chữ/logo/caption trái policy scene.", stage: "SCENES", symptoms: ["Có readable text trên monitor, nhân vật hoặc background."], errorSignatures: ["NO_READABLE_TEXT_ANYWHERE_FAIL"], firstDivergence: "FLOW_VIDEO_OUTPUT", rootCause: "Generated output không tuân text policy dù prompt đã đúng.", optimalFix: "Tạo clean video không generated readable text; nếu exact text bắt buộc, overlay deterministic sau đó.", doNotDo: ["Không dùng dirty reference.", "Không tin prompt PASS là output PASS."], validationAfterFix: ["Kiểm tra 0/25/50/75/100% và frames trung gian.", "Exact text overlay chỉ khi scene yêu cầu."], repairScope: "FRAME_REGION", tags: ["flow", "text", "video"], evidenceRequired: ["Prompt", "video frames", "text policy"], affectedComponents: ["scene generation", "validator"], createdFromIncident: "Readable text output incident" }),
  verified({ issueId: "FLOW_SMOKE_RING_OMITTED", title: "Flow bỏ qua smoke ring", description: "Vòng khói từ miệng không xuất hiện trong bất kỳ frame nào dù action đã yêu cầu.", stage: "SCENES", symptoms: ["Không thấy smoke ring 0–100%."], errorSignatures: ["SMOKE_RING_ACTION_FAIL"], firstDivergence: "FLOW_VIDEO_OUTPUT", rootCause: "Flow không thực thi detail action này.", optimalFix: "Thêm deterministic FFmpeg post-effect cục bộ từ miệng.", doNotDo: ["Không regenerate Flow chỉ để cố ép smoke ring nhiều lần."], validationAfterFix: ["Ring bắt đầu từ miệng, rõ, nở nhẹ/tan dần.", "Không đổi phần hình ảnh khác."], repairScope: "FRAME_REGION", tags: ["smoke-ring", "ffmpeg", "post-processing"], evidenceRequired: ["Video frame review", "mouth coordinates"], affectedComponents: ["post-processing"], createdFromIncident: "Scene 5 smoke ring incident" }),
  verified({ issueId: "BLINK_DOES_NOT_REOPEN", title: "Blink không reopen hoàn toàn", description: "Mắt bắt đầu nhắm nhưng không mở lại sau blink.", stage: "POST_PROCESSING", symptoms: ["Eyes remain half closed after 2.5s."], errorSignatures: ["BLINK_ACTION_FAIL"], firstDivergence: "FLOW_VIDEO_OUTPUT", rootCause: "Generated motion không hoàn tất full blink cycle.", optimalFix: "Áp dụng deterministic localized blink post-effect: open → close → reopen.", doNotDo: ["Không reverse/loop toàn bộ cơ thể."], validationAfterFix: ["Open before, closed during, fully reopened after.", "Smoke ring và các vùng khác được giữ."], repairScope: "FRAME_REGION", tags: ["blink", "eyes", "post-processing"], evidenceRequired: ["Frame-by-frame eye review"], affectedComponents: ["localized post-processing"], createdFromIncident: "Scene 5 blink incident" }),
  verified({ issueId: "GAZE_NOT_TO_MONITOR", title: "Gaze không nhìn monitor", description: "Nhân vật nhìn thẳng thay vì hướng rõ về màn hình bên trái.", stage: "POST_PROCESSING", symptoms: ["GAZE_TO_MONITOR FAIL."], errorSignatures: ["GAZE_DIRECTION_MISMATCH"], firstDivergence: "FLOW_VIDEO_OUTPUT", rootCause: "Flow giữ gaze mặc định dù scene yêu cầu target rõ.", optimalFix: "Dùng localized deterministic pupil/gaze overlay, giữ nguyên đầu/mặt và tắt overlay khi blink.", doNotDo: ["Không sửa blink hoặc smoke ring khi chỉ gaze fail.", "Không làm mắt lác."], validationAfterFix: ["Gaze to monitor rõ và tự nhiên.", "Không artefact, blink/smoke preserved."], repairScope: "FRAME_REGION", tags: ["gaze", "pupil", "monitor"], evidenceRequired: ["Eye/monitor coordinates", "timeline", "frame review"], affectedComponents: ["localized post-processing"], createdFromIncident: "Scene 5 gaze incident" }),
  verified({ issueId: "GAZE_WHITE_HALO_COMPOSITING", title: "Gaze overlay có white halo", description: "Mảng trắng cứng cạnh pupil mới làm lộ compositing.", stage: "POST_PROCESSING", symptoms: ["White halo cạnh pupil."], errorSignatures: ["GAZE_OVERLAY_COMPOSITING_FAIL"], firstDivergence: "GAZE_OVERLAY_COMPOSITING", rootCause: "Fixed white value 230 không khớp sclera thực và alpha compositing sai.", optimalFix: "Lấy real sclera patch từ source frame, mask anti-aliased đúng contour.", doNotDo: ["Không dùng fixed white patch.", "Không dùng alpha ramp để che lỗi."], validationAfterFix: ["Không halo.", "Sclera color match và pupil style match."], repairScope: "FRAME_REGION", tags: ["gaze", "halo", "compositing"], evidenceRequired: ["Source/output eye crops", "compositing parameters"], affectedComponents: ["FFmpeg overlay"], createdFromIncident: "Gaze halo incident" }),
  verified({ issueId: "DOUBLE_PUPIL_ERASURE_ALIGNMENT", title: "Double pupil", description: "Pupil cũ bị xóa thiếu khiến hai pupil cùng xuất hiện.", stage: "POST_PROCESSING", symptoms: ["Double pupil sau gaze patch."], errorSignatures: ["DOUBLE_PUPIL", "OLD_PUPIL_FULLY_ERASED_FAIL"], firstDivergence: "OLD_PUPIL_ERASURE_ALIGNMENT", rootCause: "Sclera patch lệch contour pupil cũ vài pixel.", optimalFix: "Detect contour pupil cũ chính xác, erase full pupil + anti-aliased edge rồi draw pupil mới.", doNotDo: ["Không chỉ dịch pupil mới khi pupil cũ chưa được che hết."], validationAfterFix: ["Old pupil erased.", "Double pupil absent.", "Blink/smoke preserved."], repairScope: "FRAME_REGION", tags: ["gaze", "pupil", "alignment"], evidenceRequired: ["Contour measurements", "eye frames"], affectedComponents: ["FFmpeg overlay"], createdFromIncident: "Gaze pupil alignment incident" }),
  verified({ issueId: "FINAL_ASSEMBLY_STALE_SOURCE_RISK", title: "Final Assembly có nguy cơ lấy stale/wrong source", description: "Tên file tương tự không chứng minh là approved source cuối cùng.", stage: "FINAL_ASSEMBLY", symptoms: ["Assembly có thể lấy scene-1.mp4/scene-5.mp4 stale."], errorSignatures: ["APPROVED_SOURCE_AMBIGUOUS"], firstDivergence: "ASSEMBLY", rootCause: "Assembly suy luận source từ filename thay vì manifest bất biến.", optimalFix: "Khóa immutable approved-source manifest trước Final Assembly.", doNotDo: ["Không thay source theo file mới hơn hoặc tên giống nhau.", "Không dùng temp file."], retryPolicy: boundedRetry(0), validationAfterFix: ["Manifest chứa đúng 5 path approved.", "Playlist/order khớp manifest."], repairScope: "ASSEMBLY", tags: ["assembly", "manifest", "approved"], evidenceRequired: ["Approved evidence", "manifest", "playlist"], affectedComponents: ["final assembly"], createdFromIncident: "Final assembly source-lock incident" }),
  verified({ issueId: "RECOVERY_LOOP_UNBOUNDED", title: "Recovery loop chạy vô hạn", description: "Retry không có giới hạn làm tốn thời gian/credit và phá checkpoint.", stage: "GLOBAL", symptoms: ["Stage RECOVERING lặp vô hạn hoặc quá nhiều attempts."], errorSignatures: ["RECOVERY_ATTEMPTS_EXHAUSTED", "RETRY_LOOP"], firstDivergence: "RECOVERY_POLICY", rootCause: "Retry policy không có maxAttempts/stop conditions rõ.", optimalFix: "Finite retry, backoff bounded, escalation và checkpoint preservation.", doNotDo: ["Không retry Generate vô hạn.", "Không hiển thị ∞ khi policy thực tế phải hữu hạn."], validationAfterFix: ["maxAttempts hữu hạn.", "Stop conditions và escalation được ghi."], repairScope: "GLOBAL", tags: ["retry", "recovery", "checkpoint"], evidenceRequired: ["Retry counters", "checkpoint", "escalation event"], affectedComponents: ["codex policy", "executor"], createdFromIncident: "Recovery loop control incident" }),
  verified({ issueId: "GEMINI_429_BOUNDED_BACKOFF", title: "Gemini 429", description: "Provider rate/quota failure không được biến thành semantic asset failure.", stage: "ASSETS", symptoms: ["GEMINI_QUALITY_VALIDATION_429 hoặc quota/rate limit."], errorSignatures: ["429", "quota", "rate limit"], firstDivergence: "PROVIDER", rootCause: "Provider unavailable tạm thời hoặc hạn mức API.", optimalFix: "Bounded backoff, giữ checkpoint và resume khi có thể.", doNotDo: ["Không regenerate asset như thể semantic FAIL.", "Không retry không giới hạn."], validationAfterFix: ["Retry count bounded.", "Checkpoint còn nguyên.", "Provider success mới được tiếp tục."], repairScope: "CHECKPOINT", tags: ["gemini", "429", "backoff"], evidenceRequired: ["Provider response", "retry timeline", "checkpoint"], affectedComponents: ["quality validator", "policy"], createdFromIncident: "Gemini quality validation 429 incident" }),
  verified({ issueId: "ELECTRON_IPC_UNDEFINED_SEND", title: "Electron IPC undefined send", description: "Renderer/main gọi bridge hoặc channel không tồn tại dẫn tới undefined send/invocation.", stage: "FLOW_RUNTIME", symptoms: ["IPC bridge undefined hoặc channel missing."], errorSignatures: ["IPC_UNDEFINED", "CHANNEL_NOT_FOUND"], firstDivergence: "IPC_BRIDGE", rootCause: "Preload bridge/channel chưa được validate trước invocation.", optimalFix: "Validate IPC bridge và registered channel trước invocation; trả lỗi rõ có context.", doNotDo: ["Không gọi send/invoke qua optional undefined."], validationAfterFix: ["Bridge exists.", "Channel registered.", "Invocation has structured result."], repairScope: "FLOW_RUNTIME", tags: ["electron", "ipc", "bridge"], evidenceRequired: ["Preload exposure", "main handler registration", "renderer invocation"], affectedComponents: ["electron/preload.cjs", "electron/main.cjs", "renderer"], createdFromIncident: "Electron IPC safety incident" }),
  verified({ issueId: "MALFORMED_REPAIR_PROMPT", title: "Malformed repair prompt", description: "Repair prompt thiếu cấu trúc/required state khiến provider nhận prompt không hợp lệ hoặc sửa sai phạm vi.", stage: "PROMPT", symptoms: ["Repair request JSON/prompt invalid hoặc thiếu expected state."], errorSignatures: ["REPAIR_PROMPT_INVALID", "PROMPT_CONTRACT_FAILED"], firstDivergence: "PROMPT", rootCause: "Compiled repair prompt không được validate trước submit.", optimalFix: "Validate compiled repair prompt/JSON contract trước submit; yêu cầu self-contained repair scope.", doNotDo: ["Không submit malformed prompt rồi đoán lỗi provider.", "Không sửa toàn scene nếu repair scope hẹp."], validationAfterFix: ["Schema/contract PASS trước submit.", "Prompt có required state và no-do constraints."], repairScope: "PROMPT", tags: ["repair-prompt", "validation", "contract"], evidenceRequired: ["Compiled prompt", "schema result", "expected state"], affectedComponents: ["repair prompt compiler", "validator"], createdFromIncident: "Repair prompt contract incident" }),
  verified({ issueId: "CHARACTER_IDENTITY_APPEARANCE_CONFLATION", title: "Nhầm Character Identity với Scene Appearance", description: "Compiler áp dụng trang phục canonical cho mọi scene và coi áo/quần/phụ kiện là identity bất biến.", stage: "PROJECT", symptoms: ["Scene có wardrobe sai dù identity khuôn mặt/tóc đúng."], errorSignatures: ["SCENE_APPEARANCE_MISMATCH", "PROMPT_CONTRACT_FAILED"], firstDivergence: "PROMPT", rootCause: "Character identity và scene appearance không được tách trong Expected State/prompt compiler.", optimalFix: "Khóa identity invariants riêng; lấy wardrobe, accessories và props từ Scene Expected State có thẩm quyền.", doNotDo: ["Không áp dụng global wardrobe cho mọi scene.", "Không phân loại wardrobe sai thành WRONG_CHARACTER."], validationAfterFix: ["Validator phân biệt CHARACTER_IDENTITY_MISMATCH với SCENE_APPEARANCE_MISMATCH.", "Prompt dùng wardrobe theo từng scene."], repairScope: "PROMPT", tags: ["identity", "appearance", "wardrobe"], evidenceRequired: ["Character reference", "Scene Expected State", "compiled prompt"], affectedComponents: ["expected state builder", "prompt compiler", "quality validator"], createdFromIncident: "Identity versus scene appearance correction" }),
  verified({ issueId: "FLOW_COMPOSER_NAVIGATION_AFTER_DOWNLOAD", title: "Flow vẫn ở trang xem video sau khi tải scene trước", description: "Sau download, Flow chuyển sang preview page; reload tại đó không khôi phục composer để tạo scene kế tiếp.", stage: "FLOW_RUNTIME", symptoms: ["Không tìm thấy Video settings hoặc Start khi tạo scene 2."], errorSignatures: ["FLOW_COMPOSER_NOT_FOUND_AFTER_DOWNLOAD"], firstDivergence: "FLOW_RUNTIME", rootCause: "Automation reload preview URL thay vì quay về Flow project composer URL.", optimalFix: "Trước mỗi scene tiếp theo, mở lại Flow project URL, chờ composer/settings rồi mới attach Start frame.", doNotDo: ["Không chỉ reload preview page.", "Không gửi scene tiếp theo khi composer chưa xác minh."], validationAfterFix: ["Composer hiện diện.", "Scene tiếp theo dùng đúng scene-N Start frame và video được tải về."], repairScope: "FLOW_RUNTIME", tags: ["flow", "navigation", "composer", "download"], evidenceRequired: ["Current URL", "composer DOM", "scene sequence result"], affectedComponents: ["electron/main.cjs", "Flow automation"], createdFromIncident: "Multi-scene Flow navigation incident" }),
  verified({ issueId: "ANALYSIS_VERSION_EVIDENCE_SELECTION", title: "Chọn analysis mới nhất mù thay vì bản có evidence tốt", description: "Pipeline lấy analysis version mới nhất dù nội dung degraded/không quan sát được video, làm Modeling Idea fail.", stage: "MODELING", symptoms: ["Modeling Idea invalid sau analysis chung chung hoặc degraded."], errorSignatures: ["ANALYSIS_EVIDENCE_INSUFFICIENT", "AI_STRUCTURED_OUTPUT_INVALID"], firstDivergence: "ANALYSIS", rootCause: "Selection policy ưu tiên recency mà không chấm evidence quality.", optimalFix: "Ưu tiên analysis có evidence tốt nhất; degraded analysis không được chọn mù làm input downstream.", doNotDo: ["Không mặc định lấy record mới nhất.", "Không xem analysis không quan sát được video là tương đương analysis đầy đủ."], validationAfterFix: ["Selected analysis có hook/setup/conflict/escalation/twist/payoff hoặc evidence tương đương.", "Modeling Idea parse hợp lệ."], repairScope: "GLOBAL", tags: ["analysis", "evidence", "selection"], evidenceRequired: ["Analysis versions", "evidence fields", "selected record"], affectedComponents: ["analysis service", "modeling service"], createdFromIncident: "Analysis version fallback incident" }),
];

export const VERIFIED_TROUBLESHOOTING_RULES = validateTroubleshootingRules(rules);
